<?php
declare(strict_types=1);
require_once __DIR__ . '/config/koneksi.php';
apply_security_headers(true);
if (session_status() !== PHP_SESSION_ACTIVE) session_start();
$error = trim((string)($_GET['error'] ?? ''));
$publicDemo = filter_var(env_value('PUBLIC_DEMO_ENABLED', 'true'), FILTER_VALIDATE_BOOL);
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="EnglAI mengubah RPP menjadi AI Classroom untuk Self Learning dan Live Quiz Bahasa Inggris."><title>EnglAI · AI Classroom Platform</title><link rel="stylesheet" href="/assets/css/mvp.css"><link rel="stylesheet" href="/assets/css/public-page-refresh.css"></head><body><div class="stars" aria-hidden="true"></div>
<header class="nav"><a class="brand" href="/" aria-label="EnglAI home"><span class="brand-mark">E</span>EnglAI</a><nav class="nav-links" aria-label="Navigasi utama"><a href="#features">Features</a><a href="#how">How It Works</a><a class="button secondary" href="/admin/login.php">Teacher Login</a></nav></header>
<main><section class="public-hero public-hero-centered"><span class="eyebrow">AI-POWERED ENGLISH CLASSROOM</span><h1 class="display">Transformasi Kelas Anda.<br><span class="gradient-text">Hidupkan AI Classroom.</span></h1><p class="lead">EnglAI membantu Teacher mengubah RPP menjadi Self Learning, Live Quiz, dan analisis perkembangan siswa dalam satu classroom.</p>
<section class="card join-panel join-panel-horizontal" id="join" aria-labelledby="join-title"><div><span class="eyebrow">STUDENT ACCESS</span><h2 id="join-title">Join your classroom</h2></div><?php if($error!==''):?><div class="alert error" role="alert"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></div><?php endif;?><form method="post" action="/student/join.php" data-join-form class="join-inline"><label class="sr-only" for="classroom_code">Classroom ID</label><input id="classroom_code" name="classroom_code" maxlength="16" autocomplete="off" placeholder="Enter Classroom ID" pattern="ENG-[A-Za-z0-9-]{4,8}" required><button class="button primary" type="submit">Join Classroom</button><p class="muted join-help">Belum punya Classroom ID? Hubungi Teacher.</p><p class="muted" aria-live="polite" data-join-status></p></form></section></section>
<section class="section" id="features"><div class="section-head"><span class="eyebrow">Platform Features</span><h2>Satu alur dari RPP hingga Progress</h2></div><div class="grid four"><?php foreach([['🧠','AI RPP Analysis','Menemukan fokus, vocabulary, grammar, dan level dari lesson plan.'],['📚','Self Learning','Reading, Listening, Speaking, dan Writing yang dapat digunakan kapan saja.'],['🏆','Live Quiz','Lobby multiplayer, timer server, scoring, dan Leaderboard.'],['📈','Learning Analytics','Progress nyata dari aktivitas Student.']] as $feature):?><article class="card hover feature-card"><div class="icon-box"><?=$feature[0]?></div><h3><?=$feature[1]?></h3><p class="muted"><?=$feature[2]?></p></article><?php endforeach;?></div></section>
<section class="section"><div class="section-head"><span class="eyebrow">English Skills</span><h2>Belajar sesuai skill</h2></div><div class="grid four"><?php foreach([['📖','Reading','Passage, vocabulary, comprehension, and objective feedback.'],['🎧','Listening','Generated listening audio, comprehension practice, and feedback.'],['🎤','Speaking','Speech recognition, transcript review, and AI Speaking Feedback.'],['✍️','Writing','Writing practice, word guidance, rubric assessment, and AI feedback.']] as $skill):?><article class="card hover skill-card active"><span class="badge available">Available in AI Classroom</span><div class="skill-icon"><?=$skill[0]?></div><h3><?=$skill[1]?></h3><p class="muted"><?=$skill[2]?></p><a href="#join" class="text-link">Join Classroom</a></article><?php endforeach;?></div></section>
<section class="section" id="how"><div class="section-head"><span class="eyebrow">How It Works</span><h2>Dari lesson plan ke pengalaman kelas</h2></div><div class="grid steps"><?php foreach([['Upload RPP','Teacher mengunggah PDF atau DOCX pada Classroom tertentu.'],['AI Analysis','Backend menganalisis dan menyiapkan content bank.'],['AI Classroom','Student masuk menggunakan Classroom ID yang valid.'],['Self Learning','Empat skill tersedia kapan saja.'],['Live Quiz','Teacher membuka lobby dan memulai permainan sinkron.'],['Progress','Jawaban, skor, dan hasil tersimpan sebagai data aktivitas.']] as $step):?><article class="card step"><h3><?=$step[0]?></h3><p class="muted"><?=$step[1]?></p></article><?php endforeach;?></div></section></main><footer class="public-footer"><span class="brand">EnglAI</span><p>AI Classroom Platform untuk pembelajaran Bahasa Inggris.</p></footer><script src="/assets/js/visual-effects.js" defer></script><script src="/assets/js/public.js" defer></script></body></html>
