<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config/koneksi.php';require_once dirname(__DIR__,2).'/vendor/autoload.php';
use EnglAI\Learning\ListeningSessionService;
$pdo=db();$fail=[];$ok=static function(bool$c,string$m)use(&$fail){if(!$c)$fail[]=$m;};
$fixture=$pdo->query("SELECT a.classroom_id,a.lesson_plan_id,a.level FROM learning_activities a JOIN classroom_lesson_plans p ON p.id=a.lesson_plan_id AND p.is_active=1 WHERE a.skill='listening' AND a.status='ready' GROUP BY a.classroom_id,a.lesson_plan_id,a.level HAVING COUNT(DISTINCT a.id)>=10 LIMIT 1")->fetch();if(!$fixture){fwrite(STDERR,"Listening fixture unavailable.\n");exit(1);}
$makeMember=static function(string$name)use($pdo,$fixture):int{$pdo->prepare("INSERT INTO classroom_members(classroom_id,session_token,display_name,avatar,membership_status,approved_at) VALUES(?,?,?,'reader','active',NOW())")->execute([(int)$fixture['classroom_id'],hash('sha256',$name.microtime(true).random_int(1,PHP_INT_MAX)),$name]);return(int)$pdo->lastInsertId();};$mid=$makeMember('Listening Random A');$mid2=$makeMember('Listening Random B');
try{
 $service=new ListeningSessionService($pdo);$id=$service->start((int)$fixture['classroom_id'],$mid,(string)$fixture['level']);$s=$service->get($id,$mid);$snapshot=$s['snapshot'];$questions=$snapshot['questions']??[];$ok(count($questions)===10,'Session harus tepat 10 soal.');$ok(count(array_unique(array_column($questions,'activity_id')))===10,'Question IDs harus unik.');$ok(count(array_unique(array_map(fn($q)=>ListeningSessionService::norm($q['question']),$questions)))===10,'Question texts harus unik.');$same=$service->start((int)$fixture['classroom_id'],$mid,(string)$fixture['level']);$ok($same===$id&&$service->get($same,$mid)['snapshot_json']===$s['snapshot_json'],'Continue/refresh harus mempertahankan snapshot.');
 $distribution=$snapshot['correct_distribution']??[];sort($distribution);$ok($distribution===[2,2,3,3],'Distribusi correct letters harus 3/3/2/2.');$letters=array_column($questions,'correct_letter');for($i=2;$i<10;$i++)$ok(!($letters[$i]===$letters[$i-1]&&$letters[$i]===$letters[$i-2]),'Maksimal dua correct letters sama berurutan.');foreach($questions as$q){$ok(count($q['options'])===4&&count(array_unique(array_column($q['options'],'id')))===4,'Stable option IDs harus unik.');$ok(in_array($q['correct_option_id'],array_column($q['options'],'id'),true),'Correct option harus tetap valid setelah shuffle.');}$public=json_encode($service->publicState($s));$ok(!str_contains($public,'correct_option_id')&&!str_contains($public,'explanation'),'Initial payload tidak boleh membocorkan answer key.');
 $service->play($id,$mid);$service->begin($id,$mid);$first=$questions[0];$wrong=current(array_filter(array_column($first['options'],'id'),fn($v)=>$v!==$first['correct_option_id']));$answer=$service->answer($id,$mid,(int)$first['activity_id'],(string)$wrong,false);$ok($answer['result']==='incorrect'&&$answer['current_index']===1,'Wrong answer harus maju.');$ok($service->answer($id,$mid,(int)$first['activity_id'],(string)$wrong,false)['duplicate'],'Duplicate submission harus idempotent.');for($i=1;$i<10;$i++){$q=$questions[$i];$service->play($id,$mid);$service->begin($id,$mid);$result=$service->answer($id,$mid,(int)$q['activity_id'],null,true);$ok($result['current_index']===$i+1,'Timeout harus maju.');}
 $review=$service->review($id,$mid);$ok(count($review)===10&&$review[0]['correct_answer']===$questions[0]['correct_letter'],'Review harus memakai shuffled option order snapshot.');$again=$service->start((int)$fixture['classroom_id'],$mid,(string)$fixture['level'],true);$againSnapshot=$service->get($again,$mid)['snapshot'];$ok($againSnapshot['sequence_fingerprint']!==$snapshot['sequence_fingerprint'],'Play Again harus menghasilkan urutan berbeda.');$other=$service->start((int)$fixture['classroom_id'],$mid2,(string)$fixture['level']);$otherSnapshot=$service->get($other,$mid2)['snapshot'];$ok($otherSnapshot['sequence_fingerprint']!==$snapshot['sequence_fingerprint']||json_encode($otherSnapshot['questions'][0]['options'])!==json_encode($snapshot['questions'][0]['options']),'Student berbeda harus mendapat order berbeda.');
}finally{$pdo->prepare('DELETE FROM classroom_members WHERE id IN(?,?)')->execute([$mid,$mid2]);}
$js=file_get_contents(dirname(__DIR__,2).'/assets/js/listening-game.js');$page=file_get_contents(dirname(__DIR__,2).'/student/listening.php');$source=file_get_contents(dirname(__DIR__,2).'/src/Learning/ListeningSessionService.php');$ok(str_contains($js,'const LISTENING_FEEDBACK_MS=3000')&&substr_count($js,'LISTENING_FEEDBACK_MS')>=3,'Semua feedback harus memakai constant 3000ms.');$ok(str_contains($js,'inlineFeedback(data)')&&str_contains($js,'timeoutPopup(data)'),'Correct/incorrect inline dan timeout popup harus terpisah.');$ok(str_contains($js,'musicGain.gain.value=.55')&&str_contains($js,'createDynamicsCompressor'),'Music gain dan limiter harus ditingkatkan.');$ok(str_contains($js,'duck?.004:.55')&&str_contains($js,'if(musicTimer)return'),'Ducking harus kembali ke full gain tanpa restart tiap soal.');$ok(!preg_match('/innerHTML|GEMINI_API_KEY|AIza[0-9A-Za-z_-]+/',$js.$page),'Frontend Listening harus safe tanpa secret.');$ok(str_contains($source,'balancedPositions')&&str_contains($source,'sequence_fingerprint'),'Server randomization wajib aktif.');if($fail){fwrite(STDERR,"Listening gameplay failed:\n- ".implode("\n- ",$fail)."\n");exit(1);}echo"Listening gameplay targeted OK.\n";
