<?php
declare(strict_types=1);require_once __DIR__.'/../../config/koneksi.php';require_once __DIR__.'/../../vendor/autoload.php';
use EnglAI\Auth\AccountService;use EnglAI\Mvp\ClassroomService;
$pdo=db();if(session_status()!==PHP_SESSION_ACTIVE)session_start();$fails=[];$ok=static function(bool $v,string $m)use(&$fails){echo($v?'PASS ':'FAIL ').$m.PHP_EOL;if(!$v)$fails[]=$m;};$suffix=bin2hex(random_bytes(4));$password='SecurePass'.$suffix.'9A';
$accounts=new AccountService($pdo);$tid=$accounts->register('teacher',"teacher-{$suffix}@example.test",'Test Teacher',$password);$sid=$accounts->register('student',"student-{$suffix}@example.test",'Test Student',$password);
$teacher=$accounts->login("teacher-{$suffix}@example.test",$password,'teacher');$student=$accounts->login("student-{$suffix}@example.test",$password,'student');$ok($teacher['role']==='teacher'&&$student['role']==='student','Teacher and Student permanent login');
$bad=false;try{$accounts->register('student',"bad-{$suffix}@example.test",'Bad','short');}catch(InvalidArgumentException){$bad=true;}$ok($bad,'password policy enforced');
if(session_status()!==PHP_SESSION_ACTIVE)session_start();$_SESSION['user_id']=$tid;$_SESSION['admin_username']=$teacher['email'];$classId=(new ClassroomService($pdo))->create($teacher['email'],'Phase5 Test Classroom');$class=(new ClassroomService($pdo))->requireOwned($classId,$teacher['email']);$ok((int)$class['teacher_user_id']===$tid,'Teacher ownership uses final user ID');
$token=bin2hex(random_bytes(32));$pdo->prepare("INSERT INTO classroom_members(classroom_id,user_id,session_token,membership_status,last_seen_at) VALUES(?,?,?,'active',NOW())")->execute([$classId,$sid,$token]);$member=(int)$pdo->lastInsertId();$duplicate=false;try{$pdo->prepare("INSERT INTO classroom_members(classroom_id,user_id,session_token,membership_status) VALUES(?,?,?,'active')")->execute([$classId,$sid,bin2hex(random_bytes(32))]);}catch(PDOException){$duplicate=true;}$ok($duplicate,'Student cannot join same Classroom twice');
$old=$class['code'];$new='ENG-'.strtoupper(substr(bin2hex(random_bytes(4)),0,6));$pdo->prepare('UPDATE classrooms SET code=? WHERE id=?')->execute([$new,$classId]);$pdo->prepare('INSERT INTO classroom_code_history(classroom_id,old_code,new_code,changed_by) VALUES(?,?,?,?)')->execute([$classId,$old,$new,$tid]);$ok(!(new ClassroomService($pdo))->findActiveByCode($old)&&(new ClassroomService($pdo))->findActiveByCode($new)!==false,'Classroom ID regeneration invalidates old code');
$pdo->prepare('UPDATE classrooms SET join_open=0 WHERE id=?')->execute([$classId]);$ok(!(new ClassroomService($pdo))->findActiveByCode($new),'closed Classroom rejects new joins');
$pdo->prepare("UPDATE classrooms SET status='archived',join_open=1 WHERE id=?")->execute([$classId]);$ok(!(new ClassroomService($pdo))->findActiveByCode($new),'archived Classroom rejects joins');
$chars='📖 🎧 🎤 ✍️ 🏆 🎮 ·';$ok(mb_check_encoding($chars,'UTF-8')&&mb_strlen($chars)>7,'required emoji and separator are valid UTF-8');
$pdo->prepare('DELETE FROM classrooms WHERE id=?')->execute([$classId]);$pdo->prepare('DELETE FROM users WHERE id IN (?,?)')->execute([$tid,$sid]);$pdo->prepare('DELETE FROM login_attempts WHERE identity_hash IN (?,?)')->execute([hash('sha256',"teacher-{$suffix}@example.test"),hash('sha256',"student-{$suffix}@example.test")]);
if($fails){fwrite(STDERR,implode(', ',$fails));exit(1);}
