<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config/koneksi.php';require_once dirname(__DIR__,2).'/vendor/autoload.php';
use EnglAI\Learning\AssessmentService;use EnglAI\Learning\LearningContentGenerator;use EnglAI\Learning\Level;use EnglAI\Learning\RppAnalysisService;
$pdo=db();$failures=[];$check=static function(bool $ok,string $message)use(&$failures){if(!$ok)$failures[]=$message;};
$classroom=$pdo->query('SELECT * FROM classrooms ORDER BY id LIMIT 1')->fetch();if(!$classroom)throw new RuntimeException('Demo classroom missing.');$classroomId=(int)$classroom['id'];
putenv('GEMINI_API_KEY');$analysis=(new RppAnalysisService($pdo))->analyze($classroomId);$check(in_array($analysis['recommended_level'],Level::VALUES,true),'Recommended level invalid.');$check($analysis['recommendation_reason']!=='','Recommendation reason missing.');$check($analysis['source']==='fallback','No-key analysis must use fallback.');
$generator=new LearningContentGenerator($pdo);foreach(['reading','listening','speaking','writing'] as $skill)$generator->generate($classroomId,$skill,'intermediate');$generator->generate($classroomId,'reading','basic');$generator->generate($classroomId,'reading','advanced');
$stmt=$pdo->prepare("SELECT skill,level,COUNT(*) total,COUNT(DISTINCT module_id) modules FROM learning_activities WHERE classroom_id=? GROUP BY skill,level");$stmt->execute([$classroomId]);$matrix=[];foreach($stmt->fetchAll() as $row)$matrix[$row['skill']][$row['level']]=$row;
foreach(['reading','listening','speaking','writing'] as $skill){$check((int)($matrix[$skill]['intermediate']['total']??0)>=10,"{$skill} generation below 10.");$check((int)($matrix[$skill]['intermediate']['modules']??0)>=3,"{$skill} modules below 3.");}
$stmt=$pdo->prepare("SELECT level,content_json FROM learning_activities WHERE classroom_id=? AND skill='reading' AND level IN('basic','advanced') ORDER BY id");$stmt->execute([$classroomId]);$lengths=[];foreach($stmt->fetchAll() as $row){$data=json_decode($row['content_json'],true);$lengths[$row['level']][]=str_word_count($data['passage']??'');}$check(max($lengths['advanced']??[0])>max($lengths['basic']??[0]),'Advanced passage must be longer than Basic.');
$stmt=$pdo->prepare("SELECT * FROM learning_activities WHERE classroom_id=? AND skill='speaking' LIMIT 1");$stmt->execute([$classroomId]);$speaking=$stmt->fetch();$assessment=(new AssessmentService($pdo))->assess('speaking','This response explains the lesson context with a complete sentence and relevant learning vocabulary.',$speaking);$check($assessment['source']==='fallback','No-key assessment must use fallback.');$check($assessment['total_score']>=0&&$assessment['total_score']<=100,'Assessment score out of bounds.');
$stmt=$pdo->prepare("SELECT COUNT(*) FROM learning_activities WHERE classroom_id=? AND skill='listening' AND JSON_EXTRACT(content_json,'$.transcript') IS NOT NULL");$stmt->execute([$classroomId]);$check((int)$stmt->fetchColumn()>=10,'Listening transcript missing.');
$stmt=$pdo->prepare("SELECT COUNT(*) FROM learning_activities l JOIN content_questions q ON q.classroom_id=l.classroom_id WHERE l.classroom_id=? AND q.content_type='live_quiz' AND l.content_hash=q.question_hash");$stmt->execute([$classroomId]);$check((int)$stmt->fetchColumn()===0,'Self Learning and Live Quiz hash overlap.');
try{Level::validate('expert');$check(false,'Invalid level accepted.');}catch(InvalidArgumentException){}
if($failures){fwrite(STDERR,"Phase 2 services failed:\n- ".implode("\n- ",$failures)."\n");exit(1);}echo "Phase 2 analysis, level, four-skill generation, isolation, and fallback assessment OK.\n";
