<?php
declare(strict_types=1);
require_once __DIR__.'/../config/koneksi.php';require_once __DIR__.'/../vendor/autoload.php';
use EnglAI\Audio\BrowserSpeechSynthesisProvider;use EnglAI\Learning\AssessmentService;use EnglAI\Learning\Level;use EnglAI\Learning\ProgressService;use EnglAI\Mvp\StudentSession;use EnglAI\Security\Csrf;use EnglAI\Security\RateLimiter;
$pdo=db();$member=StudentSession::requireMember($pdo);$classroomId=(int)$member['classroom_id'];$memberId=(int)$member['id'];$attemptId=(int)($_GET['attempt']??$_POST['attempt_id']??0);$error='';
if(strtolower((string)($_GET['skill']??''))==='reading'){header('Location: /student/self_learning.php?level='.rawurlencode((string)($_GET['level']??'intermediate')));exit;}
if($attemptId>0){$legacy=$pdo->prepare('SELECT l.skill FROM learning_attempts a JOIN learning_activities l ON l.id=a.activity_id WHERE a.id=? AND a.member_id=?');$legacy->execute([$attemptId,$memberId]);if($legacy->fetchColumn()==='reading'){header('Location: /student/self_learning.php');exit;}}
if($attemptId<1){$skill=strtolower((string)($_GET['skill']??''));$level=Level::validate((string)($_GET['level']??''));if(!in_array($skill,['reading','listening','speaking','writing'],true)){http_response_code(404);exit;}
  $stmt=$pdo->prepare("SELECT l.* FROM learning_activities l WHERE l.classroom_id=? AND l.skill=? AND l.level=? AND l.status='ready' AND l.id NOT IN(SELECT activity_id FROM learning_attempts WHERE member_id=? AND status='completed') ORDER BY RAND() LIMIT 1");$stmt->execute([$classroomId,$skill,$level,$memberId]);$activity=$stmt->fetch();
  if(!$activity){
      $stmt=$pdo->prepare("SELECT l.* FROM learning_activities l WHERE l.classroom_id=? AND l.skill=? AND l.level=? AND l.status='ready' ORDER BY RAND() LIMIT 1");
      $stmt->execute([$classroomId,$skill,$level]);
      $activity=$stmt->fetch();
  }
  if(!$activity){header('Location: /student/skill.php?skill='.$skill.'&message='.rawurlencode('Materi pembelajaran belum tersedia untuk skill dan level ini.'));exit;}$key=bin2hex(random_bytes(32));$stmt=$pdo->prepare("INSERT INTO learning_attempts(classroom_id,member_id,activity_id,idempotency_key,status,started_at) VALUES(?,?,?,?,'started',NOW())");$stmt->execute([$classroomId,$memberId,$activity['id'],$key]);header('Location: /student/activity.php?attempt='.(int)$pdo->lastInsertId());exit;
}
$stmt=$pdo->prepare('SELECT a.*,l.title,l.instruction,l.content_json,l.skill,l.level,l.activity_type,l.source_excerpt,l.competency FROM learning_attempts a JOIN learning_activities l ON l.id=a.activity_id WHERE a.id=? AND a.member_id=? AND a.classroom_id=?');$stmt->execute([$attemptId,$memberId,$classroomId]);$attempt=$stmt->fetch();if(!$attempt){http_response_code(404);exit('Activity tidak ditemukan.');}$content=json_decode($attempt['content_json'],true);if(!is_array($content)){http_response_code(500);exit('Activity content invalid.');}
if($_SERVER['REQUEST_METHOD']==='POST'){
 Csrf::requireValid($_POST['csrf_token']??null);if($attempt['status']==='completed'){http_response_code(409);exit('Submission sudah diproses.');}$skill=$attempt['skill'];$answerJson=null;$submission='';$score=0;$feedback='';$source='objective';$assessment=null;
 if(in_array($skill,['reading','listening'],true)){$selected=strtoupper((string)($_POST['answer']??''));if(!in_array($selected,['A','B','C','D'],true))$error='Pilih jawaban terlebih dahulu.';else{$correct=hash_equals((string)$content['answer'],$selected);$score=$correct?100:0;$feedback=(string)$content['explanation'];$answerJson=json_encode(['selected'=>$selected,'correct_answer'=>$content['answer'],'is_correct'=>$correct],JSON_UNESCAPED_UNICODE);}}
 elseif($skill==='speaking'){$submission=trim((string)($_POST['transcript']??''));if($submission===''||mb_strlen($submission)>12000)$error='Transcript wajib diisi dan maksimal 12.000 karakter.';elseif(!RateLimiter::check('assessment:'.$memberId,12,300))$error='Terlalu banyak assessment. Coba lagi beberapa menit.';else{$assessment=(new AssessmentService($pdo))->assess('speaking',$submission,$attempt);$score=$assessment['total_score'];$feedback=implode(' ',$assessment['improvements']);$source=$assessment['source'];}}
 else{$submission=trim((string)($_POST['writing']??''));$words=preg_split('/\s+/u',$submission,-1,PREG_SPLIT_NO_EMPTY)?:[];$count=count($words);$min=(int)$content['min_words'];$max=(int)$content['max_words'];if($submission===''||mb_strlen($submission)>20000)$error='Writing submission kosong atau terlalu besar.';elseif($count<$min||$count>$max)$error="Jumlah kata harus antara {$min} dan {$max}. Saat ini: {$count}.";elseif(!RateLimiter::check('assessment:'.$memberId,12,300))$error='Terlalu banyak assessment. Coba lagi beberapa menit.';else{$assessment=(new AssessmentService($pdo))->assess('writing',$submission,$attempt);$score=$assessment['total_score'];$feedback=implode(' ',$assessment['improvements']);$source=$assessment['source'];}}
 if($error===''){$pdo->beginTransaction();try{$stmt=$pdo->prepare("UPDATE learning_attempts SET status='completed',answer_json=?,transcript=?,writing_submission=?,score=?,feedback=?,assessment_source=?,submitted_at=NOW(),completed_at=NOW() WHERE id=? AND status='started'");$stmt->execute([$answerJson,$skill==='speaking'?$submission:null,$skill==='writing'?$submission:null,$score,$feedback,$source,$attemptId]);if($stmt->rowCount()!==1)throw new RuntimeException('Duplicate submission.');if($assessment){$stmt=$pdo->prepare('INSERT INTO assessment_results(attempt_id,skill,criteria_json,total_score,maximum_score,strengths_json,improvements_json,grammar_notes_json,vocabulary_notes_json,suggested_revision,example_answer,confidence,source,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$stmt->execute([$attemptId,$skill,json_encode($assessment['criteria'],JSON_UNESCAPED_UNICODE),$assessment['total_score'],100,json_encode($assessment['strengths'],JSON_UNESCAPED_UNICODE),json_encode($assessment['improvements'],JSON_UNESCAPED_UNICODE),json_encode($assessment['grammar_notes'],JSON_UNESCAPED_UNICODE),json_encode($assessment['vocabulary_notes'],JSON_UNESCAPED_UNICODE),$assessment['suggested_revision'],(string)($content['example_answer']??$content['example_response']??''),$assessment['confidence'],$assessment['source'],$assessment['status']]);}$pdo->commit();(new ProgressService($pdo))->refresh($classroomId,$memberId,$skill,$attempt['level'],(int)$attempt['activity_id']);header('Location: /student/activity.php?attempt='.$attemptId);exit;}catch(Throwable $e){$pdo->rollBack();if(str_contains($e->getMessage(),'Duplicate')){http_response_code(409);exit('Submission sudah diproses.');}throw $e;}}
}
$assessmentResult=null;
$hasMore=false;
if($attempt['status']==='completed'){
    $stmt=$pdo->prepare('SELECT * FROM assessment_results WHERE attempt_id=?');
    $stmt->execute([$attemptId]);
    $assessmentResult=$stmt->fetch();
    
    $stmt=$pdo->prepare("SELECT COUNT(*) FROM learning_activities WHERE classroom_id=? AND skill=? AND level=? AND status='ready' AND id NOT IN (SELECT activity_id FROM learning_attempts WHERE member_id=? AND status='completed')");
    $stmt->execute([$classroomId,$attempt['skill'],$attempt['level'],$memberId]);
    $hasMore=((int)$stmt->fetchColumn() > 0);
}$audio=$attempt['skill']==='listening'?(new BrowserSpeechSynthesisProvider())->configuration($content):null;
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($attempt['title'])?> · EnglAI</title><link rel="stylesheet" href="/assets/css/mvp.css"></head>
<body data-activity-skill="<?=htmlspecialchars($attempt['skill'])?>" data-attempt-id="<?=$attemptId?>" data-result-accuracy="<?=$attempt['status']==='completed'?(float)$attempt['score']:''?>"><div class="stars" aria-hidden="true"></div><header class="nav"><a class="brand" href="/student/dashboard.php"><span class="brand-mark">E</span>EnglAI</a><a class="button secondary" href="/student/skill.php?skill=<?=$attempt['skill']?>&level=<?=$attempt['level']?>">← <?=ucfirst($attempt['skill'])?></a></header>
<main class="game-shell"><div class="row"><span class="badge available"><?=ucfirst($attempt['skill'])?></span><span class="badge dev"><?=ucfirst($attempt['level'])?></span><span class="status"><?=htmlspecialchars($attempt['competency'])?></span></div>
<?php if($error):?><div class="alert error" role="alert" style="margin-top:16px"><?=htmlspecialchars($error)?></div><?php endif;?>
<?php if($attempt['status']==='completed'):?><section class="card game-card" style="margin-top:18px"><span class="eyebrow">Activity Completed</span><h1 class="gradient-text"><?=htmlspecialchars($attempt['title'])?></h1><div class="stat" style="font-size:4rem"><?=(int)$attempt['score']?>/100</div><p class="lead"><?=htmlspecialchars((string)$attempt['feedback'])?></p>
<?php if(in_array($attempt['skill'],['reading','listening'],true)):$answer=json_decode((string)$attempt['answer_json'],true);?><div class="analysis-item"><b>Your answer:</b> <?=htmlspecialchars($answer['selected']??'—')?> · <b>Correct:</b> <?=htmlspecialchars($answer['correct_answer']??'—')?></div><div class="analysis-item" style="margin-top:10px"><b>Explanation:</b> <?=htmlspecialchars($content['explanation'])?></div><?php if($attempt['skill']==='listening'):?><div class="analysis-item" style="margin-top:10px"><b>Transcript unlocked:</b><p><?=htmlspecialchars($content['transcript']??$content['script'])?></p></div><?php endif;?>
<?php elseif($assessmentResult):$criteria=json_decode($assessmentResult['criteria_json'],true)?:[];?><span class="badge <?=$assessmentResult['source']==='ai'?'available':'dev'?>">Assessment · <?=htmlspecialchars($assessmentResult['source'])?></span><div class="grid two" style="margin-top:18px"><?php foreach($criteria as $criterion):?><div class="analysis-item"><b><?=htmlspecialchars(str_replace('_',' ',ucfirst($criterion['name'])))?></b><div class="progress-track"><div class="progress-fill" style="width:<?=max(0,min(100,(float)$criterion['score']))?>%"></div></div><small><?=number_format((float)$criterion['score'],0)?>/100 · <?=htmlspecialchars($criterion['feedback'])?></small></div><?php endforeach;?></div><div class="analysis-item" style="margin-top:16px"><b>Suggested revision</b><p><?=htmlspecialchars($assessmentResult['suggested_revision'])?></p></div><details><summary>Example answer</summary><p><?=htmlspecialchars($assessmentResult['example_answer'])?></p></details><?php endif;?>
<div class="row" style="margin-top:22px; align-items: center; gap: 10px;"><?php if($hasMore): ?><a class="button gold" href="/student/activity.php?skill=<?=$attempt['skill']?>&level=<?=$attempt['level']?>">Next Activity</a><?php else: ?><span class="badge available" style="padding:12px; font-size:0.95rem; font-weight:bold; vertical-align:middle; display:inline-block; line-height:1.2; margin:0;">✓ All Activities Completed!</span><a class="button gold" href="/student/activity.php?skill=<?=$attempt['skill']?>&level=<?=$attempt['level']?>" style="margin:0;">Repeat / Retake Activity →</a><?php endif; ?><a class="button secondary" href="/student/progress.php" style="margin:0;">View Progress</a></div></section>
<?php else:?><section class="card game-card" style="margin-top:18px"><span class="eyebrow"><?=htmlspecialchars($attempt['instruction'])?></span><h1><?=htmlspecialchars($attempt['title'])?></h1>
<?php if($attempt['skill']==='reading'):?><div class="analysis-item"><p><?=htmlspecialchars($content['passage'])?></p></div><p class="question"><?=htmlspecialchars($content['question'])?></p>
<?php elseif($attempt['skill']==='listening'):?><div class="listening-player" data-listening data-script="<?=htmlspecialchars($content['script'])?>" data-language="<?=htmlspecialchars($audio['language'])?>" data-rate="<?=$audio['rate']?>" data-pitch="<?=$audio['pitch']?>" data-max-replays="<?=$audio['max_replays']?>"><div class="waveform" aria-hidden="true"><?php for($i=0;$i<18;$i++):?><i></i><?php endfor;?></div><button type="button" class="button gold" data-audio-play>▶ Generated Listening Audio</button><span class="muted" data-audio-status aria-live="polite">Transcript locked until submission · <?=$audio['max_replays']?> replays available</span></div><p class="question"><?=htmlspecialchars($content['question'])?></p>
<?php elseif($attempt['skill']==='speaking'):?><div class="analysis-item"><b>Scenario</b><p><?=htmlspecialchars($content['scenario'])?></p></div><p class="question"><?=htmlspecialchars($content['prompt'])?></p><div class="alert ok">Consent: microphone hanya digunakan browser untuk menghasilkan transcript. Audio tidak disimpan oleh EnglAI.</div>
<?php else:?><div class="analysis-item"><b>Context</b><p><?=htmlspecialchars($content['context'])?></p></div><p class="question"><?=htmlspecialchars($content['prompt'])?></p><?php endif;?>
<form method="post" data-activity-form><?=Csrf::field()?><input type="hidden" name="attempt_id" value="<?=$attemptId?>">
<?php if(in_array($attempt['skill'],['reading','listening'],true)):?><div class="choices"><?php foreach($content['options'] as $i=>$option):$letter=chr(65+$i);?><button class="choice" name="answer" value="<?=$letter?>"><b><?=$letter?></b><span><?=htmlspecialchars($option)?></span></button><?php endforeach;?></div>
<?php elseif($attempt['skill']==='speaking'):?><div class="row"><button type="button" class="button primary" data-mic>🎙 Start Microphone</button><button type="button" class="button secondary" data-mic-retry>Retry</button></div><p class="muted" data-speech-status aria-live="polite">Jika Speech Recognition tidak didukung, ketik transcript manual.</p><label for="transcript">Transcript preview</label><textarea id="transcript" name="transcript" rows="8" maxlength="12000" data-transcript required></textarea><small class="muted">Minimum guidance: <?=$content['min_words']?> words · AI Speaking Feedback tidak menilai phoneme, stress, intonation, accent, atau pronunciation accuracy.</small><button class="button gold wide" style="margin-top:18px" data-submit>Request AI Speaking Feedback</button>
<?php else:?><label for="writing">Writing response</label><textarea id="writing" name="writing" rows="15" maxlength="20000" data-writing data-min="<?=$content['min_words']?>" data-max="<?=$content['max_words']?>" required></textarea><div class="row" style="justify-content:space-between"><span data-word-count>0 words · target <?=$content['min_words']?>–<?=$content['max_words']?></span><span class="muted" data-autosave aria-live="polite">Draft not saved</span></div><button class="button gold wide" style="margin-top:18px" data-submit>Submit for AI Review</button><?php endif;?></form></section><?php endif;?>
</main><script src="/assets/js/visual-effects.js" defer></script><script src="/assets/js/learning-activities.js" defer></script></body></html>
