<?php
declare(strict_types=1);
require_once __DIR__.'/../config/koneksi.php';require_once __DIR__.'/../vendor/autoload.php';
use EnglAI\Mvp\StudentSession;$pdo=db();$member=StudentSession::requireMember($pdo);$classroomId=(int)$member['classroom_id'];
$stmt=$pdo->prepare("SELECT q.* FROM quiz_sessions q WHERE q.classroom_id=? AND q.state IN ('LOBBY','COUNTDOWN','ACTIVE','BETWEEN_QUESTIONS','EVALUATING') ORDER BY q.id DESC LIMIT 1");$stmt->execute([$classroomId]);$quiz=$stmt->fetch();
$stmt=$pdo->prepare("SELECT COUNT(*) completed,COALESCE(AVG(score),0) average_score,COALESCE(MAX(score),0) best_score FROM student_learning_sessions WHERE member_id=? AND status='completed'");$stmt->execute([(int)$member['id']]);$progress=$stmt->fetch();
$stmt=$pdo->prepare("SELECT COUNT(*) FROM content_questions WHERE classroom_id=? AND content_type='self_learning'");$stmt->execute([$classroomId]);$bank=(int)$stmt->fetchColumn();
$stmt=$pdo->prepare("SELECT original_name FROM classroom_lesson_plans WHERE classroom_id=? AND is_active=1 ORDER BY version DESC LIMIT 1");$stmt->execute([$classroomId]);$lesson=$stmt->fetchColumn()?:'Lesson plan sedang disiapkan';
$stmt=$pdo->prepare("SELECT s.score,s.completed_at FROM student_learning_sessions s WHERE s.member_id=? AND s.status='completed' ORDER BY s.id DESC LIMIT 1");$stmt->execute([(int)$member['id']]);$recent=$stmt->fetch();
$stmt=$pdo->prepare("SELECT p.display_name,p.avatar,p.total_score FROM quiz_participants p JOIN quiz_sessions q ON q.id=p.quiz_session_id WHERE q.classroom_id=? AND q.state IN ('FINISHED','CLOSED') ORDER BY p.total_score DESC LIMIT 5");$stmt->execute([$classroomId]);$leaders=$stmt->fetchAll();
$accuracy=(int)round((float)$progress['average_score']);$level=$accuracy>=80?'Advanced':($accuracy>=50?'Intermediate':'Basic');
$stmt=$pdo->prepare("SELECT skill,level,COUNT(*) available FROM learning_activities WHERE classroom_id=? AND status='ready' GROUP BY skill,level");$stmt->execute([$classroomId]);$phase2=[];foreach($stmt->fetchAll() as $item)$phase2[$item['skill']][$item['level']]=$item;
$stmt=$pdo->prepare("SELECT skill,COUNT(*) completed,COALESCE(AVG(score),0) average_score,MAX(score) latest_score FROM learning_attempts a JOIN learning_activities l ON l.id=a.activity_id WHERE a.member_id=? AND a.status='completed' GROUP BY skill");$stmt->execute([(int)$member['id']]);$phase2Progress=array_column($stmt->fetchAll(),null,'skill');
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Student Classroom · EnglAI</title><link rel="stylesheet" href="/assets/css/mvp.css"></head>
<body><div class="stars" aria-hidden="true"></div><header class="nav"><a class="brand" href="/student/dashboard.php"><span class="brand-mark">E</span>EnglAI</a><div class="row"><span class="badge available">Student</span><a class="button secondary" href="/student/logout.php">Leave Classroom</a></div></header>
<main class="shell"><nav class="breadcrumb"><a href="/">Public</a><span>›</span><strong><?=htmlspecialchars($member['classroom_name'])?></strong></nav>
<section class="card student-hero"><div class="toolbar"><div><span class="code"><?=htmlspecialchars($member['classroom_code'])?></span><h1><?=htmlspecialchars($member['classroom_name'])?></h1><p class="muted">Teacher · <?=htmlspecialchars((string)db()->query('SELECT teacher_key FROM classrooms WHERE id='.$classroomId)->fetchColumn())?> · <?=htmlspecialchars((string)$lesson)?></p></div><?php if($quiz):?><span class="badge live"><?=$quiz['state']==='LOBBY'?'Live Quiz Ready':'Live Now'?></span><?php endif;?></div>
<div class="row" style="justify-content:space-between"><span>Learning Progress</span><b><?=$accuracy?>%</b></div><div class="progress-track"><div class="progress-fill" data-progress="<?=$accuracy?>"></div></div></section>
<nav class="student-nav glass" aria-label="Student sections"><a class="active" href="#dashboard">Dashboard</a><?php foreach(['reading','listening','speaking','writing'] as $navSkill):?><?php if(isset($phase2[$navSkill])):?><a href="/student/skill.php?skill=<?=$navSkill?>"><?=ucfirst($navSkill)?></a><?php else:?><span class="disabled"><?=ucfirst($navSkill)?> · Not Generated</span><?php endif;?><?php endforeach;?><a href="/student/progress.php">Progress</a><a href="#leaderboard">Leaderboard</a><a href="#live-quiz">Live Quiz</a></nav>
<section id="dashboard" class="grid four"><article class="card metric"><div class="icon-box">⚡</div><div><div class="stat"><?=(int)$progress['completed']?></div><span class="muted">Sessions</span></div></article><article class="card metric"><div class="icon-box">🎯</div><div><div class="stat"><?=$accuracy?>%</div><span class="muted">Average</span></div></article><article class="card metric"><div class="icon-box">🏅</div><div><div class="stat"><?=(int)$progress['best_score']?></div><span class="muted">Best Score</span></div></article><article class="card metric"><div class="icon-box">📊</div><div><div class="stat" style="font-size:1rem"><?=$level?></div><span class="muted">Current Level</span></div></article></section>
<section class="grid two" style="margin-top:22px"><article class="card recommend"><span class="eyebrow">Recommended Activity</span><h2>Reading Self Learning</h2><p class="muted">Latih vocabulary dan comprehension melalui activity dari lesson plan Classroom.</p><?php if(isset($phase2['reading'])):?><a class="button gold" href="/student/skill.php?skill=reading">Open Reading Modules</a><?php elseif($bank>=10):?><a class="button gold" href="/student/self_learning.php">Open Reading Practice</a><?php else:?><span class="badge dev">Teacher is preparing content</span><?php endif;?></article>
<article class="card" id="live-quiz"><span class="eyebrow">Live Quiz</span><h2><?=$quiz?($quiz['state']==='LOBBY'?'Lobby is ready':'Quiz in progress'):'Belum ada sesi live'?></h2><p class="muted"><?=$quiz?'Pilih identity, join lobby, dan tunggu Teacher memulai permainan.':'Status diperbarui ketika Teacher membuka lobby.'?></p><?php if($quiz):?><a class="button primary" href="/student/quiz_join.php?id=<?=(int)$quiz['id']?>"><?=$quiz['state']==='LOBBY'?'Join Live Quiz':'Reconnect to Quiz'?></a><?php else:?><span class="status">Offline</span><?php endif;?></article></section>
<div class="toolbar" style="margin-top:34px"><div><span class="eyebrow">Learning Skills</span><h2>Pilih skill pembelajaran</h2></div></div><section class="grid four">
<?php foreach([['📖','reading'],['🎧','listening'],['🎤','speaking'],['✍️','writing']] as $skillData):$skillName=$skillData[1];$availableLevels=$phase2[$skillName]??[];$skillProgress=$phase2Progress[$skillName]??null;$done=(int)($skillProgress['completed_activities']??0);$status=!$availableLevels?'Not Generated':($done>0?'In Progress':'Available');?><article class="card <?=$availableLevels?'hover':''?>" id="<?=$skillName?>"><span class="badge <?=$availableLevels?'available':'dev'?>"><?=$status?></span><div class="skill-icon"><?=$skillData[0]?></div><h3><?=ucfirst($skillName)?></h3><p class="muted"><?=count($availableLevels)?> level tersedia · <?=number_format((float)($skillProgress['average_score']??0),0)?>% average</p><?php if($availableLevels):?><a class="button primary wide" href="/student/skill.php?skill=<?=$skillName?>">Continue Learning</a><?php endif;?></article><?php endforeach;?></section>
<section class="grid two" style="margin-top:22px"><article class="card" id="progress"><h2>Recent Result</h2><?php if($recent):?><div class="stat"><?=(int)$recent['score']?>/100</div><p class="muted">Self Learning · <?=htmlspecialchars($recent['completed_at'])?></p><span class="badge <?=(int)$recent['score']>=70?'available':'dev'?>"><?=(int)$recent['score']>=70?'Completed':'Keep Practicing'?></span><?php else:?><div class="empty">Selesaikan Self Learning pertama Anda.</div><?php endif;?></article>
<article class="card" id="leaderboard"><h2>Leaderboard</h2><?php if(!$leaders):?><div class="empty">Leaderboard muncul setelah Live Quiz selesai.</div><?php else:?><ol class="leaderboard"><?php foreach($leaders as $i=>$leader):?><li><b>#<?=$i+1?></b><span><?=htmlspecialchars($leader['avatar'].' '.$leader['display_name'])?></span><b><?=(int)$leader['total_score']?></b></li><?php endforeach;?></ol><?php endif;?></article></section>
</main><script src="/assets/js/visual-effects.js" defer></script><script src="/assets/js/student.js" defer></script></body></html>
