<?php
declare(strict_types=1);
require_once __DIR__.'/../config/koneksi.php';require_once __DIR__.'/../vendor/autoload.php';
use EnglAI\Learning\ListeningSessionService;use EnglAI\Learning\Level;use EnglAI\Mvp\StudentSession;use EnglAI\Security\Csrf;
$pdo=db();$member=StudentSession::requireMember($pdo);$mid=(int)$member['id'];$cid=(int)$member['classroom_id'];$service=new ListeningSessionService($pdo);$level='';$error='';try{$level=Level::validate((string)($_GET['level']??'intermediate'));}catch(Throwable){$error='Level Listening tidak valid.';}$id=(int)($_GET['session']??$_POST['session_id']??0);
if(!$id&&(isset($_GET['start'])||isset($_GET['continue'])||isset($_GET['play_again']))){try{
$stmt = $pdo->prepare("SELECT completed_at FROM listening_sessions WHERE member_id=? AND classroom_id=? AND level=? AND status='completed' ORDER BY completed_at DESC LIMIT 1");
$stmt->execute([$mid, $cid, $level]);
$lastCompleted = $stmt->fetchColumn();
if ($lastCompleted) {
    $elapsed = time() - strtotime((string)$lastCompleted);
    if ($elapsed < 60) {
        throw new RuntimeException("Harap tunggu " . (60 - $elapsed) . " detik lagi sebelum memulai ulang latihan ini.");
    }
    $pdo->beginTransaction();
    try {
        $pdo->prepare("DELETE FROM listening_session_answers WHERE listening_session_id IN (SELECT id FROM listening_sessions WHERE member_id = ? AND classroom_id = ? AND level = ?)")->execute([$mid, $cid, $level]);
        $pdo->prepare("DELETE FROM learning_attempts WHERE member_id = ? AND classroom_id = ? AND activity_id IN (SELECT id FROM learning_activities WHERE skill='listening' AND level=?)")->execute([$mid, $cid, $level]);
        $pdo->prepare("DELETE FROM listening_sessions WHERE member_id = ? AND classroom_id = ? AND level = ?")->execute([$mid, $cid, $level]);
        $pdo->commit();
    } catch (\Throwable $ex) {
        $pdo->rollBack();
        throw $ex;
    }
}
$id=$service->start($cid,$mid,$level,isset($_GET['play_again']));header('Location: /student/listening.php?session='.$id);exit;}catch(Throwable$e){$error=$e->getMessage();}}
if($_SERVER['REQUEST_METHOD']==='POST'){header('Content-Type: application/json; charset=UTF-8');if(!Csrf::validate($_POST['csrf_token']??null)){http_response_code(419);echo json_encode(['success'=>false,'code'=>'CSRF_INVALID','message'=>'Session keamanan berakhir.']);exit;}try{$action=(string)($_POST['action']??'answer');if($action==='play')$out=$service->play($id,$mid);elseif($action==='begin'){$service->begin($id,$mid);$out=['success'=>true];}else$out=$service->answer($id,$mid,(int)($_POST['activity_id']??0),isset($_POST['answer'])?(string)$_POST['answer']:null,($_POST['timed_out']??'')==='1');echo json_encode($out,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}catch(Throwable$e){$code=$e->getMessage();http_response_code(in_array($code,['STALE_QUESTION','PLAY_LIMIT'],true)?409:422);app_log('warning','Listening gameplay request rejected',['session_id'=>$id,'member_id'=>$mid,'code'=>$code]);echo json_encode(['success'=>false,'code'=>$code,'message'=>$code==='PLAY_LIMIT'?'Audio sudah diputar dua kali.':'Request Listening tidak dapat diproses.']);exit;}}
$session=null;$state=null;$review=[];if($id){try{$session=$service->get($id,$mid);$state=$service->publicState($session);if($session['status']==='completed')$review=$service->review($id,$mid);}catch(Throwable$e){$error=$e->getMessage();}}function lh(mixed$v):string{return htmlspecialchars((string)($v??''),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}$csrf=Csrf::token();
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Listening Self Learning · EnglAI</title><link rel="stylesheet" href="/assets/css/mvp.css"><link rel="stylesheet" href="/assets/css/listening-game.css"></head><body data-listening-game data-session-id="<?=$id?>" data-csrf="<?=lh($csrf)?>"><div class="stars"></div><header class="nav"><a class="brand" href="/student/dashboard.php">EnglAI</a><?php if($session):?><div class="row"><span class="badge available">Listening</span><span class="badge"><?=lh(ucfirst((string)$session['level']))?></span><span>Question <b data-question-count><?=min((int)$session['current_position']+1,10)?></b> of 10 · Score <b data-score><?=(int)$session['score']?></b></span></div><?php endif;?></header><main class="game-shell" data-listening-stage>
<?php if($error):?><section class="card empty"><h1>Listening belum tersedia</h1><p><?=lh($error)?></p><a class="button secondary" href="/student/skill.php?skill=listening">Kembali</a></section>
<?php elseif(!$session):?><section class="card game-card"><span class="eyebrow">LISTENING SELF LEARNING</span><h1>Ready to listen?</h1><p>10 questions · 10 seconds after first audio · maximum two plays.</p><a class="button gold" href="/student/listening.php?start=1&amp;level=<?=lh($level)?>">Start Listening</a></section>
<?php elseif($session['status']==='completed'): $correct=count(array_filter($review,fn($r)=>$r['result']==='correct'));$timeouts=count(array_filter($review,fn($r)=>$r['result']==='timed_out'));$duration=max(0,strtotime((string)$session['completed_at'])-strtotime((string)$session['started_at']));?><section class="card result-card"><span class="eyebrow">COMPLETED 10/10</span><h1>Listening Result · <?=lh(ucfirst((string)$session['level']))?></h1><div class="grid four"><div class="analysis-item"><b><?=(int)$session['score']?>/100</b><br>Score</div><div class="analysis-item"><b><?=$correct?></b><br>Correct</div><div class="analysis-item"><b><?=10-$correct-$timeouts?></b><br>Incorrect</div><div class="analysis-item"><b><?=$timeouts?></b><br>Timed Out</div></div><p>Accuracy <?=round($correct/10*100)?>% · Duration <?=floor($duration/60)?>m <?=$duration%60?>s</p><div class="row"><a class="button gold" href="/student/listening.php?play_again=1&amp;level=<?=lh($session['level'])?>">Play Again</a><a class="button secondary" href="/student/skill.php?skill=listening">Choose Another Level</a><a class="button secondary" href="/student/dashboard.php">Back to Classroom</a></div></section><section class="card" id="review"><h2>Review Answers</h2><?php foreach($review as$i=>$r):$answerClass=$r['result']==='correct'?'review-correct':($r['result']==='incorrect'?'review-wrong':'review-timeout');?><article class="review-item <?=$answerClass?>"><span class="badge <?=$r['result']==='correct'?'available':'dev'?>">Question <?=$i+1?> · <?=lh(ucwords(str_replace('_',' ',$r['result'])))?></span><h3><?=lh($r['question'])?></h3><button type="button" class="button secondary" data-review-audio data-script="<?=lh($r['script'])?>">▶ Replay Audio</button><p>Your answer: <b class="student-answer"><?=lh($r['selected_answer_text']??'No answer — Time’s up')?></b></p><p>Correct answer: <b class="correct-answer"><?=lh($r['correct_answer_text'])?></b></p><p><?=lh($r['explanation'])?></p><small>+<?=(int)$r['score']?> points · <?=number_format((int)$r['response_ms']/1000,1)?>s</small></article><?php endforeach;?></section>
<?php else:?><section class="listening-game" data-initial-state='<?=lh(json_encode($state,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?>'></section><?php endif;?></main><div class="feedback-overlay" data-feedback-overlay hidden role="dialog" aria-modal="true" aria-live="assertive"><div class="feedback-popup timed_out" data-feedback-popup><div class="feedback-symbol" data-feedback-symbol>⏱</div><h2 data-feedback-title>TIME’S UP!</h2><p data-feedback-detail></p><p>Loading the next question...</p><b data-feedback-countdown>3</b></div></div><script src="/assets/js/visual-effects.js" defer></script><script src="/assets/js/listening-game.js" defer></script></body></html>
