<?php
declare(strict_types=1);require_once __DIR__.'/../config/koneksi.php';require_once __DIR__.'/../vendor/autoload.php';
use EnglAI\Analytics\AnalyticsService;use EnglAI\Learning\ProgressService;use EnglAI\Mvp\StudentSession;
$member=StudentSession::requireMember(db());$cid=(int)$member['classroom_id'];$mid=(int)$member['id'];$summary=(new ProgressService(db()))->summary($cid,$mid);$rows=$summary['rows'];$recommended=$summary['recommended'];$analytics=(new AnalyticsService(db()))->student($cid,$mid);
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Progress · EnglAI</title><link rel="stylesheet" href="/assets/css/mvp.css"><link rel="stylesheet" href="/assets/css/analytics.css"></head><body><div class="stars" aria-hidden="true"></div><header class="nav"><a class="brand" href="/student/dashboard.php"><span class="brand-mark">E</span>EnglAI</a><a class="button secondary" href="/student/dashboard.php">← Classroom</a></header><main class="shell"><nav class="breadcrumb"><a href="/student/dashboard.php">Classroom</a><span>›</span><strong>Progress</strong></nav>
<section class="card student-hero"><span class="eyebrow">Real Activity Data</span><h1>Learning Progress</h1><p class="muted">Data hanya berasal dari activity attempts dan Live Quiz result identity session Anda.</p></section>
<?php if($recommended):?><section class="card recommend"><span class="eyebrow">Recommended Next Activity</span><h2><?=ucfirst($recommended['skill'])?> · <?=ucfirst($recommended['level'])?></h2><a class="button gold" href="/student/skill.php?skill=<?=$recommended['skill']?>&level=<?=$recommended['level']?>">Continue Learning</a></section><?php endif;?>
<section class="card" style="margin-top:22px"><table><thead><tr><th>Skill</th><th>Level</th><th>Completed</th><th>Available</th><th>Average</th><th>Progress</th></tr></thead><tbody><?php foreach($rows as $row):$pct=$row['available']?round($row['completed']/$row['available']*100):0;?><tr><td><a href="/student/skill.php?skill=<?=$row['skill']?>&level=<?=$row['level']?>"><?=ucfirst($row['skill'])?></a></td><td><?=ucfirst($row['level'])?></td><td><?=(int)$row['completed']?></td><td><?=(int)$row['available']?></td><td><?=number_format((float)$row['average_score'],1)?>%</td><td><div class="progress-track" role="img" aria-label="<?=$pct?> percent"><span style="width:<?=$pct?>%"></span></div></td></tr><?php endforeach;?></tbody></table></section>
<section class="grid two" style="margin-top:22px"><article class="card"><h2>Personal Insight</h2><?php if(!$analytics['skills']):?><div class="empty">Belum cukup aktivitas untuk membuat analisis.</div><?php else:?><p>Strongest skill: <b><?=ucfirst((string)$analytics['strongest_skill'])?></b></p><p>Skill to improve: <b><?=ucfirst((string)$analytics['weakest_skill'])?></b></p><?php endif;?></article><article class="card"><h2>Achievements</h2><?php $ach=array_values(array_filter(array_column($analytics['quiz_history'],'achievement')));if(!$ach):?><div class="empty">Selesaikan Live Quiz untuk memperoleh achievement.</div><?php else:?><div class="row"><?php foreach(array_unique($ach) as $a):?><span class="badge available"><?=htmlspecialchars($a)?></span><?php endforeach;?></div><?php endif;?></article></section>
<section class="card" style="margin-top:22px"><h2>Live Quiz History</h2><table><thead><tr><th>Quiz</th><th>Mode</th><th>Rank</th><th>Score</th><th>Achievement</th></tr></thead><tbody><?php foreach($analytics['quiz_history'] as $q):?><tr><td><?=htmlspecialchars($q['title']?:'Quiz #'.$q['id'])?></td><td><?=htmlspecialchars(str_replace('_',' ',$q['quiz_mode']?:'reading'))?></td><td>#<?=htmlspecialchars((string)($q['final_rank']?:'—'))?></td><td><?=(int)$q['total_score']?></td><td><?=htmlspecialchars($q['achievement']?:'—')?></td></tr><?php endforeach;?></tbody></table></section></main><script src="/assets/js/visual-effects.js" defer></script></body></html>
