<?php
declare(strict_types=1);
require_once __DIR__.'/../config/koneksi.php';require_once __DIR__.'/../vendor/autoload.php';
use EnglAI\Mvp\StudentSession;use EnglAI\Security\Csrf;
$pdo=db();$member=StudentSession::requireMember($pdo);$quizId=(int)($_GET['id']??$_POST['quiz_id']??0);
$stmt=$pdo->prepare("SELECT q.*,c.name classroom_name,c.code classroom_code FROM quiz_sessions q JOIN classrooms c ON c.id=q.classroom_id WHERE q.id=? AND q.classroom_id=? AND q.state IN ('LOBBY','COUNTDOWN','ACTIVE','BETWEEN_QUESTIONS','EVALUATING')");$stmt->execute([$quizId,(int)$member['classroom_id']]);$quiz=$stmt->fetch();if(!$quiz){header('Location: /student/dashboard.php');exit;}
$stmt=$pdo->prepare('SELECT * FROM quiz_participants WHERE quiz_session_id=? AND member_id=?');$stmt->execute([$quizId,(int)$member['id']]);$existing=$stmt->fetch();if($existing){header('Location: /student/quiz_play.php?id='.$quizId);exit;}
$avatars=['🦊','🐼','🐯','🐧','🦉','🐬'];if($_SERVER['REQUEST_METHOD']==='POST'){Csrf::requireValid($_POST['csrf_token']??null);$name=trim((string)($_POST['display_name']??''));$avatar=(string)($_POST['avatar']??'');if($name===''||mb_strlen($name)>60||!in_array($avatar,$avatars,true)){$error='Masukkan display name dan pilih avatar.';}else{try{$stmt=$pdo->prepare('INSERT INTO quiz_participants(quiz_session_id,member_id,display_name,avatar,last_seen_at,joined_at) VALUES(?,?,?,?,NOW(),NOW())');$stmt->execute([$quizId,(int)$member['id'],$name,$avatar]);$pdo->prepare('UPDATE classroom_members SET display_name=?,avatar=? WHERE id=?')->execute([$name,$avatar,(int)$member['id']]);header('Location: /student/quiz_play.php?id='.$quizId);exit;}catch(PDOException){header('Location: /student/quiz_play.php?id='.$quizId);exit;}}}
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Join Live Quiz · EnglAI</title><link rel="stylesheet" href="/assets/css/mvp.css"></head><body><div class="stars" aria-hidden="true"></div><header class="nav"><a class="brand" href="/student/dashboard.php"><span class="brand-mark">E</span>EnglAI</a><span class="badge live">Live Quiz Ready</span></header>
<main class="game-shell"><nav class="breadcrumb"><a href="/student/dashboard.php">Classroom</a><span>›</span><strong>Live Quiz Lobby</strong></nav><section class="card game-card"><div style="text-align:center"><span class="eyebrow"><?=htmlspecialchars($quiz['classroom_code'])?></span><h1 class="game-title">Choose your player identity</h1><p class="muted"><?=htmlspecialchars($quiz['classroom_name'])?> · Quiz #<?=$quizId?></p></div><?php if(isset($error)):?><div class="alert error" role="alert"><?=htmlspecialchars($error)?></div><?php endif;?>
<form method="post"><?=Csrf::field()?><input type="hidden" name="quiz_id" value="<?=$quizId?>"><label for="display_name">Display name</label><input id="display_name" name="display_name" maxlength="60" autocomplete="nickname" placeholder="Nama yang terlihat di Leaderboard" required><fieldset style="border:0;padding:0"><legend style="font-weight:600;margin-bottom:10px">Pilih avatar</legend><div class="avatar-grid"><?php foreach($avatars as $avatar):?><label class="player"><input type="radio" name="avatar" value="<?=htmlspecialchars($avatar)?>" required style="width:auto"><span class="avatar"><?=$avatar?></span></label><?php endforeach;?></div></fieldset><button class="button gold wide" style="margin-top:22px">Join Lobby →</button></form></section></main><script src="/assets/js/visual-effects.js" defer></script></body></html>
