<?php
declare(strict_types=1);
require_once __DIR__.'/../config/koneksi.php';require_once __DIR__.'/../vendor/autoload.php';
use EnglAI\Mvp\StudentSession;use EnglAI\Security\Csrf;
$member=StudentSession::requireMember(db());$quizId=(int)($_GET['id']??0);$stmt=db()->prepare('SELECT p.*,q.classroom_id FROM quiz_participants p JOIN quiz_sessions q ON q.id=p.quiz_session_id WHERE p.quiz_session_id=? AND p.member_id=? AND q.classroom_id=?');$stmt->execute([$quizId,(int)$member['id'],(int)$member['classroom_id']]);$participant=$stmt->fetch();if(!$participant){header('Location: /student/dashboard.php');exit;}
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Live Quiz · EnglAI</title><link rel="stylesheet" href="/assets/css/mvp.css"><link rel="stylesheet" href="/assets/css/game.css"><link rel="stylesheet" href="/assets/css/phase3.css"></head>
<body data-quiz-role="student" data-quiz-id="<?=$quizId?>" data-csrf="<?=htmlspecialchars(Csrf::token())?>"><div class="stars" aria-hidden="true"></div><header class="nav"><a class="brand" href="/student/dashboard.php"><span class="brand-mark">E</span>EnglAI</a><div class="row"><span><?=htmlspecialchars($participant['avatar'].' '.$participant['display_name'])?></span><span id="state" class="badge live" aria-live="polite">LOBBY</span></div></header>
<main class="game-shell"><div class="game-top"><div><span class="eyebrow">Live Quiz · Reading</span><div class="game-progress"><span style="width:100%"></span></div></div><div class="timer-ring" aria-label="Server timer"><svg width="70" height="70" viewBox="0 0 70 70"><circle class="timer-bg" cx="35" cy="35" r="30"></circle><circle id="timer-value" class="timer-value" cx="35" cy="35" r="30"></circle></svg><span id="timer-text" class="timer-text">—</span></div></div>
<section id="game" class="card game-card" aria-live="polite"><span class="eyebrow">Live Quiz Lobby</span><h1>Menunggu Teacher…</h1><p class="muted">Tetap di halaman ini. Quiz dimulai otomatis.</p></section><p id="live-status" class="muted" aria-live="assertive"></p>
<section class="card" style="margin-top:18px"><div id="podium" class="podium" hidden></div><h2>Leaderboard</h2><ol id="leaderboard" class="leaderboard" aria-live="polite"></ol></section></main>
<button class="button secondary music-toggle" type="button" data-music-toggle aria-label="Toggle background music" aria-pressed="false">♪</button><script src="/assets/js/visual-effects.js" defer></script><script src="/assets/js/live-quiz.js" defer></script></body></html>
