<?php
declare(strict_types=1);
require_once __DIR__.'/../config/koneksi.php';require_once __DIR__.'/../vendor/autoload.php';
use EnglAI\Mvp\StudentSession;
$member=StudentSession::requireMember(db());$quizId=(int)($_GET['id']??0);
$q=db()->prepare("SELECT p.id participant_id,q.*,c.name classroom_name FROM quiz_participants p JOIN quiz_sessions q ON q.id=p.quiz_session_id JOIN classrooms c ON c.id=q.classroom_id WHERE q.id=? AND p.member_id=? AND q.classroom_id=? AND q.state IN ('FINISHED','CLOSED') AND q.review_enabled=1");
$q->execute([$quizId,(int)$member['id'],(int)$member['classroom_id']]);$quiz=$q->fetch();if(!$quiz){http_response_code(404);exit('Review tidak tersedia.');}
$q=db()->prepare('SELECT s.position,s.skill,s.question_type,s.question,s.content_json,s.answer,s.explanation,a.selected_answer,a.score,a.transcript,a.writing_submission,a.rubric_json,a.assessment_source FROM quiz_session_questions s LEFT JOIN quiz_answers a ON a.session_question_id=s.id AND a.participant_id=? WHERE s.quiz_session_id=? ORDER BY s.position');$q->execute([(int)$quiz['participant_id'],$quizId]);$rows=$q->fetchAll();
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Personal Quiz Review · EnglAI</title><link rel="stylesheet" href="/assets/css/mvp.css"><link rel="stylesheet" href="/assets/css/phase3.css"></head>
<body><div class="stars" aria-hidden="true"></div><header class="nav"><a class="brand" href="/student/dashboard.php"><span class="brand-mark">E</span>EnglAI</a><a class="button secondary" href="/student/dashboard.php">← Classroom</a></header><main class="shell"><section class="card dashboard-hero"><span class="eyebrow">Private Personal Review</span><h1><?=htmlspecialchars($quiz['title']?:'Live Quiz')?> Review</h1><p class="muted">Hanya jawaban, transcript, rubric, dan skor Anda sendiri yang ditampilkan.</p></section>
<?php foreach($rows as $row):$content=json_decode((string)$row['content_json'],true)?:[];$rubric=json_decode((string)($row['rubric_json']??''),true)?:[];?><article class="card" style="margin-top:16px"><div class="row"><span class="badge available"><?=htmlspecialchars(ucfirst($row['skill']))?></span><span class="badge">#<?=((int)$row['position'])+1?></span><b><?=(int)$row['score']?> / 1000</b></div><h2><?=htmlspecialchars($row['question'])?></h2>
<?php if(in_array($row['question_type'],['objective','listening_objective'],true)):?><p>Jawaban Anda: <b><?=htmlspecialchars((string)($row['selected_answer']??'Timeout'))?></b> · Correct answer: <b><?=htmlspecialchars($row['answer'])?></b></p><p class="muted"><?=htmlspecialchars($row['explanation'])?></p><?php if($row['question_type']==='listening_objective'):?><details><summary>Listening transcript</summary><p><?=htmlspecialchars((string)($content['script']??''))?></p></details><?php endif;?>
<?php elseif($row['question_type']==='speaking_response'):?><p><b>Your transcript</b></p><p><?=htmlspecialchars((string)$row['transcript'])?></p><p class="muted">AI Speaking Feedback · <?=htmlspecialchars((string)$row['assessment_source'])?></p>
<?php else:?><p><b>Your writing</b></p><p><?=nl2br(htmlspecialchars((string)$row['writing_submission']))?></p><p class="muted">Writing assessment · <?=htmlspecialchars((string)$row['assessment_source'])?></p><?php endif;?>
<?php if($rubric):?><details><summary>Personal rubric result</summary><p><?=htmlspecialchars((string)($rubric['suggested_revision']??''))?></p></details><?php endif;?></article><?php endforeach;?></main><script src="/assets/js/visual-effects.js" defer></script></body></html>
