<?php
declare(strict_types=1);
require_once __DIR__.'/../config/koneksi.php';require_once __DIR__.'/../vendor/autoload.php';
use EnglAI\Mvp\StudentSession;use EnglAI\Security\Csrf;
$pdo=db();$member=StudentSession::requireMember($pdo);$memberId=(int)$member['id'];$classroomId=(int)$member['classroom_id'];$feedback=null;$setup=!isset($_GET['new'],$_GET['id'])&&$_SERVER['REQUEST_METHOD']!=='POST';
$bankStmt=$pdo->prepare("SELECT COUNT(*) FROM content_questions WHERE classroom_id=? AND content_type='self_learning'");$bankStmt->execute([$classroomId]);$bankCount=(int)$bankStmt->fetchColumn();
if(isset($_GET['new'])){
 $recent=$pdo->prepare('SELECT DISTINCT a.question_id FROM student_learning_answers a JOIN student_learning_sessions s ON s.id=a.learning_session_id WHERE s.member_id=? AND a.question_id IS NOT NULL ORDER BY a.id DESC LIMIT 30');$recent->execute([$memberId]);$ids=array_map('intval',$recent->fetchAll(PDO::FETCH_COLUMN));
 $params=[$classroomId];$not='';if($ids){$not=' AND id NOT IN ('.implode(',',array_fill(0,count($ids),'?')).')';$params=array_merge($params,$ids);}
 $stmt=$pdo->prepare("SELECT * FROM content_questions WHERE classroom_id=? AND content_type='self_learning'{$not} ORDER BY RAND() LIMIT 10");$stmt->execute($params);$questions=$stmt->fetchAll();
 if(count($questions)<10){$stmt=$pdo->prepare("SELECT * FROM content_questions WHERE classroom_id=? AND content_type='self_learning' ORDER BY RAND() LIMIT 10");$stmt->execute([$classroomId]);$questions=$stmt->fetchAll();}
 if(count($questions)<10){header('Location: /student/dashboard.php');exit;}
 $payload=[];foreach($questions as $q){$options=json_decode($q['options_json'],true);$correct=$options[ord($q['answer'])-65];shuffle($options);$newAnswer=chr(65+array_search($correct,$options,true));$payload[]=['id'=>(int)$q['id'],'question'=>$q['question'],'options'=>$options,'answer'=>$newAnswer,'explanation'=>$q['explanation'],'difficulty'=>$q['difficulty']];}
 $stmt=$pdo->prepare("INSERT INTO student_learning_sessions(classroom_id,member_id,status,current_index,score,total_questions,question_payload_json,started_at) VALUES(?,?,'active',0,0,10,?,NOW())");$stmt->execute([$classroomId,$memberId,json_encode($payload,JSON_UNESCAPED_UNICODE)]);header('Location: /student/self_learning.php?id='.(int)$pdo->lastInsertId());exit;
}
$session=null;$payload=[];$sessionId=(int)($_GET['id']??$_POST['session_id']??0);
if(!$setup){$stmt=$pdo->prepare('SELECT * FROM student_learning_sessions WHERE id=? AND member_id=?');$stmt->execute([$sessionId,$memberId]);$session=$stmt->fetch();if(!$session){header('Location: /student/dashboard.php');exit;}$payload=json_decode($session['question_payload_json'],true);}
if($_SERVER['REQUEST_METHOD']==='POST'&&$session){
 Csrf::requireValid($_POST['csrf_token']??null);$index=(int)$session['current_index'];$question=$payload[$index]??null;$selected=strtoupper((string)($_POST['answer']??''));
 if(!$question||!in_array($selected,['A','B','C','D'],true)){http_response_code(400);exit('Jawaban tidak valid.');}$correct=hash_equals($question['answer'],$selected);
 try{$pdo->beginTransaction();$ins=$pdo->prepare('INSERT INTO student_learning_answers(learning_session_id,question_id,selected_answer,is_correct,score,answered_at) VALUES(?,?,?,?,?,NOW())');$ins->execute([$sessionId,$question['id'],$selected,$correct?1:0,$correct?10:0]);$next=$index+1;$done=$next>=count($payload);$up=$pdo->prepare("UPDATE student_learning_sessions SET current_index=?,score=score+?,status=?,completed_at=IF(?='completed',NOW(),NULL) WHERE id=?");$up->execute([$next,$correct?10:0,$done?'completed':'active',$done?'completed':'active',$sessionId]);$pdo->commit();$feedback=['correct'=>$correct,'explanation'=>$question['explanation'],'done'=>$done,'selected'=>$selected,'answer'=>$question['answer']];$session['current_index']=$next;$session['score']=(int)$session['score']+($correct?10:0);$session['status']=$done?'completed':'active';}catch(PDOException){if($pdo->inTransaction())$pdo->rollBack();http_response_code(409);exit('Jawaban sudah diproses.');}
}
$index=$session?(int)$session['current_index']:0;$question=$payload[$index]??null;$answers=[];
if($session&&$session['status']==='completed'&&!$feedback){$stmt=$pdo->prepare('SELECT question_id,selected_answer,is_correct FROM student_learning_answers WHERE learning_session_id=? ORDER BY id');$stmt->execute([$sessionId]);$answers=$stmt->fetchAll();}$score=$session?(int)$session['score']:0;$correctCount=(int)round($score/10);$accuracy=$session?(int)round($score/max(1,(int)$session['total_questions']*10)*100):0;
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Self Learning · EnglAI</title><link rel="stylesheet" href="/assets/css/mvp.css"></head>
<body data-result-accuracy="<?=$session&&$session['status']==='completed'?$accuracy:''?>"><div class="stars" aria-hidden="true"></div><header class="nav"><a class="brand" href="/student/dashboard.php"><span class="brand-mark">E</span>EnglAI</a><div class="row"><span class="badge available">Reading</span><?php if($session):?><span class="status">Score <?=$score?>/100</span><?php endif;?></div></header>
<main class="game-shell">
<?php if($setup):?><nav class="breadcrumb"><a href="/student/dashboard.php">Classroom</a><span>›</span><strong>Self Learning Setup</strong></nav><section class="card game-card"><span class="eyebrow">Ready to learn?</span><h1 class="game-title">Reading Self Learning</h1><p class="lead">Latihan individual dari Self Learning Content Bank Classroom Anda.</p><div class="grid four" style="margin:28px 0"><div class="analysis-item"><small class="muted">Skill</small><br><b>Reading</b></div><div class="analysis-item"><small class="muted">Level</small><br><b>Mixed</b></div><div class="analysis-item"><small class="muted">Questions</small><br><b>10</b></div><div class="analysis-item"><small class="muted">Est. Duration</small><br><b>5–8 min</b></div></div><p class="muted"><?=$bankCount?> questions tersedia · opsi diacak · hasil tersimpan</p><a class="button gold wide" href="/student/self_learning.php?new=1">Start Learning →</a></section>
<?php elseif($feedback):?><section class="card game-card feedback-card"><div class="feedback-icon"><?=$feedback['correct']?'✨':'💡'?></div><span class="badge <?=$feedback['correct']?'available':'dev'?>"><?=$feedback['correct']?'Correct':'Needs Review'?></span><h1><?=$feedback['correct']?'Excellent!':'Keep learning'?></h1><p class="lead"><?=htmlspecialchars($feedback['explanation'])?></p><div class="analysis-item"><b>Your answer:</b> <?=htmlspecialchars($feedback['selected'])?> · <b>Correct:</b> <?=htmlspecialchars($feedback['answer'])?></div><div style="margin-top:22px"><?php if($feedback['done']):?><a class="button gold" href="/student/self_learning.php?id=<?=$sessionId?>">View Session Result</a><?php else:?><a class="button primary" href="/student/self_learning.php?id=<?=$sessionId?>">Next Question →</a><?php endif;?></div></section>
<?php elseif($session&&$session['status']==='completed'):?><section class="card game-card" style="text-align:center"><span class="eyebrow">Session Complete</span><h1 class="gradient-text">Great work!</h1><div class="stat" style="font-size:4rem"><?=$score?>/100</div><div class="grid four" style="margin:25px 0;text-align:left"><div class="analysis-item"><small class="muted">Correct</small><br><b><?=$correctCount?></b></div><div class="analysis-item"><small class="muted">Incorrect</small><br><b><?=10-$correctCount?></b></div><div class="analysis-item"><small class="muted">Accuracy</small><br><b><?=$accuracy?>%</b></div><div class="analysis-item"><small class="muted">XP</small><br><b>+<?=$score?></b></div></div><div class="row" style="justify-content:center"><a class="button gold" href="/student/self_learning.php?new=1">Play Again</a><a class="button secondary" href="/student/dashboard.php">Back to Classroom</a></div></section>
<section class="card" style="margin-top:18px"><h2>Review Answers</h2><?php foreach($answers as $i=>$answer):$review=$payload[$i]??null;if(!$review)continue;?><div class="activity"><span><b><?=($answer['is_correct']?'✓':'×')?> <?=htmlspecialchars($review['question'])?></b><br><small class="muted">Your answer <?=htmlspecialchars((string)$answer['selected_answer'])?> · Correct <?=htmlspecialchars($review['answer'])?></small></span><span class="badge <?=$answer['is_correct']?'available':'dev'?>"><?=$answer['is_correct']?'Correct':'Review'?></span></div><?php endforeach;?></section>
<?php elseif($question):$progress=round(($index)/count($payload)*100);?><div class="game-top"><div><div class="row" style="justify-content:space-between"><span class="eyebrow">Question <?=$index+1?> / <?=count($payload)?></span><span class="muted"><?=$progress?>%</span></div><div class="game-progress"><span style="width:<?=$progress?>%"></span></div></div><button class="button secondary music-toggle" type="button" data-music-toggle aria-label="Toggle background music" aria-pressed="false">♪</button></div>
<section class="card game-card"><div class="row"><span class="badge available">Reading</span><span class="badge dev"><?=htmlspecialchars(ucfirst($question['difficulty']??'medium'))?></span></div><p class="question"><?=htmlspecialchars($question['question'])?></p><form method="post"><?=Csrf::field()?><input type="hidden" name="session_id" value="<?=$sessionId?>"><div class="choices"><?php foreach($question['options'] as $i=>$option):$letter=chr(65+$i);?><button class="choice" name="answer" value="<?=$letter?>"><b><?=$letter?></b><span><?=htmlspecialchars($option)?></span></button><?php endforeach;?></div></form></section><?php endif;?>
</main><script src="/assets/js/visual-effects.js" defer></script><script src="/assets/js/self-learning.js" defer></script></body></html>
