<?php
declare(strict_types=1);
require_once __DIR__.'/../config/koneksi.php';require_once __DIR__.'/../vendor/autoload.php';
use EnglAI\Learning\Level;use EnglAI\Learning\ProgressService;use EnglAI\Mvp\StudentSession;
$pdo=db();$member=StudentSession::requireMember($pdo);$skill=strtolower((string)($_GET['skill']??'reading'));if(!in_array($skill,['reading','listening','speaking','writing'],true)){http_response_code(404);exit('Skill tidak tersedia.');}if($skill==='reading'){$query=trim((string)($_GET['level']??''))!==''?'?level='.rawurlencode((string)$_GET['level']):'';header('Location: /student/self_learning.php'.$query);exit;}

$classroomId=(int)$member['classroom_id'];$stmt=$pdo->prepare("SELECT default_level FROM classrooms WHERE id=?");$stmt->execute([$classroomId]);$defaultLevel=(string)$stmt->fetchColumn();
$stmt=$pdo->prepare("SELECT level,COUNT(DISTINCT module_id) modules,COUNT(*) activities FROM learning_activities WHERE classroom_id=? AND skill=? AND status='ready' GROUP BY level");$stmt->execute([$classroomId,$skill]);$available=array_column($stmt->fetchAll(),null,'level');$level=(string)($_GET['level']??$defaultLevel);if(!isset($available[$level])&&$available)$level=(string)array_key_first($available);if($available)$level=Level::validate($level);
$progress=(new ProgressService($pdo))->summary($classroomId,(int)$member['id']);$row=null;foreach($progress['rows'] as $item)if($item['skill']===$skill&&$item['level']===$level)$row=$item;
$icons=['reading'=>'📖','listening'=>'🎧','speaking'=>'🎙️','writing'=>'✍️'];$descriptions=['reading'=>'Comprehension, vocabulary, inference, dan objective feedback.','listening'=>'Generated Listening Audio, locked transcript, dan comprehension.','speaking'=>'AI Speaking Feedback berdasarkan transcript, relevance, grammar, dan vocabulary.','writing'=>'Structured writing prompt dengan rubric dan backend AI review.'];
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=ucfirst($skill)?> · EnglAI</title><link rel="stylesheet" href="/assets/css/mvp.css"></head><body><div class="stars" aria-hidden="true"></div><header class="nav"><a class="brand" href="/student/dashboard.php"><span class="brand-mark">E</span>EnglAI</a><a class="button secondary" href="/student/dashboard.php">← Classroom</a></header>
<main class="shell"><nav class="breadcrumb"><a href="/student/dashboard.php">Classroom</a><span>›</span><strong><?=ucfirst($skill)?></strong></nav><?php if ($msg = trim((string)($_GET['message'] ?? ''))): ?><div class="alert success" role="status" style="margin-bottom: 22px;"><?= htmlspecialchars($msg) ?></div><?php endif; ?><section class="card student-hero"><div class="row"><div class="skill-icon"><?=$icons[$skill]?></div><div><span class="eyebrow">Self Learning Skill</span><h1><?=ucfirst($skill)?></h1><p class="muted"><?=$descriptions[$skill]?></p></div></div></section>
<section class="grid two"><article class="card"><h2>Pilih level tersedia</h2><?php if(!$available):?><div class="alert error">Teacher belum melakukan generation untuk skill ini.</div><?php else:?><div class="row"><?php foreach($available as $key=>$data):?><a class="button <?=$key===$level?'primary':'secondary'?>" href="?skill=<?=$skill?>&level=<?=$key?>"><?=ucfirst($key)?> · <?=(int)$data['activities']?></a><?php endforeach;?></div><div class="analysis-grid" style="margin-top:22px"><div class="analysis-item"><small class="muted">Modules</small><br><b><?=(int)$available[$level]['modules']?></b></div><div class="analysis-item"><small class="muted">Activities</small><br><b><?=(int)$available[$level]['activities']?></b></div><div class="analysis-item"><small class="muted">Completed</small><br><b><?=(int)($row['completed']??0)?></b></div><div class="analysis-item"><small class="muted">Average</small><br><b><?=number_format((float)($row['average_score']??0),1)?>%</b></div></div><?php if ($row && (int)$row['completed'] >= (int)$available[$level]['activities']): ?>
<div style="display:flex; flex-direction:column; gap:10px; margin-top:22px;">
    <span class="badge available" style="display:block; text-align:center; padding:12px; font-size:1.05rem; font-weight:bold; margin:0;">✓ Level Completed</span>
    <a class="button gold wide" style="margin:0;" href="<?=$skill==='listening'?'/student/listening.php?play_again=1&amp;level='.$level:($skill==='speaking'?'/student/speaking.php?play_again=1&amp;level='.$level:($skill==='writing'?'/student/writing.php?play_again=1&amp;level='.$level:'/student/activity.php?skill='.$skill.'&amp;level='.$level.'&amp;repeat=1'))?>">Repeat / Practice Again →</a>
</div>
<?php else: ?><a class="button gold wide" style="margin-top:22px" href="<?=$skill==='listening'?'/student/listening.php?continue=1&amp;level='.$level:($skill==='speaking'?'/student/speaking.php?level='.$level:($skill==='writing'?'/student/writing.php?level='.$level:'/student/activity.php?skill='.$skill.'&amp;level='.$level))?>">Continue Learning →</a><?php endif; ?><?php endif;?></article>
<article class="card recommend"><span class="eyebrow">Recommended Activity</span><h2><?=ucfirst($level?:$defaultLevel)?> <?=ucfirst($skill)?></h2><p class="muted">Aktivitas yang belum selesai diprioritaskan. Aktivitas terakhir tidak langsung diulang jika pilihan lain tersedia.</p><div class="progress-track"><div class="progress-fill" data-progress="<?=($row&&$row['available'])?round($row['completed']/$row['available']*100):0?>"></div></div></article></section></main><script src="/assets/js/visual-effects.js" defer></script><script src="/assets/js/student.js" defer></script></body></html>
