<?php
declare(strict_types=1);
require_once __DIR__.'/../config/koneksi.php';require_once __DIR__.'/../vendor/autoload.php';
use EnglAI\Learning\{AssessmentService,Level,ProgressService,SpeakingSessionService};use EnglAI\Mvp\StudentSession;use EnglAI\Security\Csrf;
$pdo=db();$member=StudentSession::requireMember($pdo);$mid=(int)$member['id'];$cid=(int)$member['classroom_id'];$service=new SpeakingSessionService($pdo);
function speaking_json(array $data,int $status=200):never{http_response_code($status);header('Content-Type: application/json; charset=UTF-8');echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(($_POST['action']??'')==='no_response'){try{Csrf::requireValid($_POST['csrf_token']??null);$noSid=(int)($_POST['session_id']??0);$noTask=(int)($_POST['task_id']??0);$noSession=$service->get($noSid,$mid,$cid);$noTasks=json_decode((string)$noSession['task_snapshot_json'],true)?:[];$noCurrent=$noTasks[(int)$noSession['current_position']]??null;if(!$noCurrent||(int)$noCurrent['id']!==$noTask)throw new RuntimeException('Task tidak sesuai session.');$pdo->prepare("UPDATE speaking_sessions SET current_position=current_position+1,task_started_at=NULL,task_deadline_at=NULL,recording_started_at=NULL,status=IF(current_position+1>=10,'completed','active'),completed_at=IF(current_position+1>=10,NOW(),NULL) WHERE id=? AND task_deadline_at<=NOW() AND NOT EXISTS(SELECT 1 FROM speaking_recordings r WHERE r.session_id=speaking_sessions.id AND r.task_id=?)")->execute([$noSid,$noTask]);speaking_json(['success'=>true,'state'=>$service->state($service->get($noSid,$mid,$cid))]);}catch(Throwable $e){speaking_json(['success'=>false,'message'=>$e->getMessage()],422);}}
 try{Csrf::requireValid($_POST['csrf_token']??null);$sid=(int)($_POST['session_id']??0);$task=(int)($_POST['task_id']??0);$action=(string)($_POST['action']??'upload');$session=$service->get($sid,$mid,$cid);$tasks=json_decode((string)$session['task_snapshot_json'],true)?:[];$current=$tasks[(int)$session['current_position']]??null;if($session['status']!=='active'||!$current||(int)$current['id']!==$task)throw new RuntimeException('Task tidak sesuai session.');if($action==='ready'){$pdo->prepare('UPDATE speaking_sessions SET task_started_at=COALESCE(task_started_at,NOW()),task_deadline_at=COALESCE(task_deadline_at,DATE_ADD(NOW(),INTERVAL 25 SECOND)) WHERE id=?')->execute([$sid]);speaking_json(['success'=>true,'state'=>$service->state($service->get($sid,$mid,$cid))]);}if($action==='recording_start'){$q=$pdo->prepare("UPDATE speaking_sessions SET recording_started_at=NOW() WHERE id=? AND recording_started_at IS NULL AND task_deadline_at>NOW()");$q->execute([$sid]);if($q->rowCount()!==1)throw new RuntimeException('Kesempatan merekam tidak tersedia atau waktu habis.');speaking_json(['success'=>true,'state'=>$service->state($service->get($sid,$mid,$cid))]);}if($action==='no_response'){$pdo->prepare("UPDATE speaking_sessions SET current_position=current_position+1,task_started_at=NULL,task_deadline_at=NULL,recording_started_at=NULL,status=IF(current_position+1>=10,'completed','active'),completed_at=IF(current_position+1>=10,NOW(),NULL) WHERE id=? AND recording_started_at IS NULL AND task_deadline_at<=NOW()")->execute([$sid]);speaking_json(['success'=>true,'state'=>$service->state($service->get($sid,$mid,$cid))]);}$duration=max(0,(int)($_POST['duration_ms']??0));$key=(string)($_POST['idempotency_key']??'');$rawTranscript=trim((string)($_POST['raw_transcript']??''));$confidence=max(0,min(1,(float)($_POST['transcript_confidence']??0)));$normalizedTranscript=preg_replace('/\s+/u',' ',$rawTranscript)??$rawTranscript;if(!preg_match('/^[a-f0-9]{64}$/',$key)||$duration<250||$duration>26000)throw new RuntimeException('Durasi rekaman tidak valid.');if(mb_strlen($rawTranscript)>12000)throw new RuntimeException('Transkrip terlalu panjang.');if($session['recording_started_at']===null)throw new RuntimeException('Kesempatan recording belum dimulai.');
  $existing=$pdo->prepare('SELECT id FROM speaking_recordings WHERE session_id=? AND task_id=?');$existing->execute([$sid,$task]);if($existing->fetchColumn())speaking_json(['success'=>true,'idempotent'=>true,'state'=>$service->state($service->get($sid,$mid,$cid))]);
  if(!isset($_FILES['audio'])||($_FILES['audio']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('Audio upload gagal.');$file=$_FILES['audio'];$size=(int)$file['size'];if($size<256||$size>5*1024*1024)throw new RuntimeException('Ukuran audio tidak valid.');$finfo=new finfo(FILEINFO_MIME_TYPE);$mime=(string)$finfo->file($file['tmp_name']);$allowed=['audio/webm','video/webm','audio/ogg','audio/mp4','video/mp4','application/octet-stream'];if(!in_array($mime,$allowed,true))throw new RuntimeException('Format audio tidak didukung.');
  $dir=dirname(__DIR__).'/storage/private/speaking/'.date('Y/m');if(!is_dir($dir)&&!mkdir($dir,0770,true)&&!is_dir($dir))throw new RuntimeException('Private storage unavailable.');$name=bin2hex(random_bytes(24)).'.webm';$path=$dir.'/'.$name;if(!move_uploaded_file($file['tmp_name'],$path))throw new RuntimeException('Audio tidak dapat disimpan.');$relative='speaking/'.date('Y/m').'/'.$name;
  $assessment=null;$score=null;$assessmentStatus=$rawTranscript===''?'needs_review':'pending';$a=$pdo->prepare('SELECT * FROM learning_activities WHERE id=? AND classroom_id=?');$a->execute([$task,$cid]);$activity=$a->fetch();if($activity&&$rawTranscript!==''){$activity['response_duration_ms']=$duration;$assessment=(new AssessmentService($pdo))->assess('speaking',$normalizedTranscript,$activity);$score=(float)$assessment['total_score'];$assessmentStatus=($confidence<0.35||$assessment['status']!=='completed')?'needs_review':'completed';}
  $transcriptionStatus=$rawTranscript===''?'needs_review':($confidence<0.35?'needs_review':'completed');$pdo->beginTransaction();try{$pdo->prepare('INSERT INTO speaking_recordings(session_id,task_id,member_id,classroom_id,idempotency_key,storage_path,mime_type,duration_ms,file_size,raw_transcript,final_transcript,transcript_confidence,transcription_status,assessment_status,assessment_json,score,consented_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW())')->execute([$sid,$task,$mid,$cid,$key,$relative,$mime,$duration,$size,$rawTranscript,$normalizedTranscript,$confidence,$transcriptionStatus,$assessmentStatus,$assessment?json_encode($assessment,JSON_UNESCAPED_UNICODE):null,$score,date('Y-m-d H:i:s')]);$next=(int)$session['current_position']+1;$done=$next>=SpeakingSessionService::TASKS;$pdo->prepare('UPDATE speaking_sessions SET current_position=?,status=?,completed_at=?,task_started_at=NULL,task_deadline_at=NULL,recording_started_at=NULL WHERE id=? AND current_position=?')->execute([$next,$done?'completed':'active',$done?date('Y-m-d H:i:s'):null,$sid,(int)$session['current_position']]);$pdo->commit();if($done)(new ProgressService($pdo))->refresh($cid,$mid,'speaking',$session['level'],$task);}catch(Throwable $e){$pdo->rollBack();@unlink($path);throw $e;}
  speaking_json(['success'=>true,'message'=>'Recording saved','state'=>$service->state($service->get($sid,$mid,$cid))]);
 }catch(Throwable $e){app_log('warning','Speaking upload rejected',['member_id'=>$mid,'error'=>get_class($e)]);speaking_json(['success'=>false,'message'=>$e->getMessage()],422);}
}
$level=Level::validate((string)($_GET['level']??'intermediate'));$sid=(int)($_GET['session']??0);try{
if(!$sid){
    $stmt = $pdo->prepare("SELECT completed_at FROM speaking_sessions WHERE member_id=? AND classroom_id=? AND level=? AND status='completed' ORDER BY completed_at DESC LIMIT 1");
    $stmt->execute([$mid, $cid, $level]);
    $lastCompleted = $stmt->fetchColumn();
    if ($lastCompleted) {
        $elapsed = time() - strtotime((string)$lastCompleted);
        if ($elapsed < 60) {
            throw new RuntimeException("Harap tunggu " . (60 - $elapsed) . " detik lagi sebelum memulai ulang latihan ini.");
        }
        $pdo->beginTransaction();
        try {
            $stmtDel = $pdo->prepare("SELECT storage_path FROM speaking_recordings WHERE session_id IN (SELECT id FROM speaking_sessions WHERE member_id = ? AND classroom_id = ? AND level = ?)");
            $stmtDel->execute([$mid, $cid, $level]);
            foreach ($stmtDel->fetchAll(PDO::FETCH_COLUMN) as $sp) {
                $fullPath = dirname(__DIR__) . '/storage/private/' . $sp;
                if (is_file($fullPath)) {
                    @unlink($fullPath);
                }
            }
            $pdo->prepare("DELETE FROM speaking_recordings WHERE session_id IN (SELECT id FROM speaking_sessions WHERE member_id = ? AND classroom_id = ? AND level = ?)")->execute([$mid, $cid, $level]);
            $pdo->prepare("DELETE FROM learning_attempts WHERE member_id = ? AND classroom_id = ? AND activity_id IN (SELECT id FROM learning_activities WHERE skill='speaking' AND level=?)")->execute([$mid, $cid, $level]);
            $pdo->prepare("DELETE FROM speaking_sessions WHERE member_id = ? AND classroom_id = ? AND level = ?")->execute([$mid, $cid, $level]);
            $pdo->commit();
        } catch (\Throwable $ex) {
            $pdo->rollBack();
            throw $ex;
        }
    }
    $session=$service->start($mid,$cid,$level,isset($_GET['play_again']));
}else{
    $session=$service->get($sid,$mid,$cid);
}
$state=$service->state($session);}catch(Throwable $e){header('Location: /student/skill.php?skill=speaking&message='.rawurlencode($e->getMessage()));exit;}
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Speaking · EnglAI</title><link rel="stylesheet" href="/assets/css/mvp.css"><link rel="stylesheet" href="/assets/css/speaking-game.css"></head><body><div class="stars" aria-hidden="true"></div><header class="nav"><a class="brand" href="/student/dashboard.php"><span class="brand-mark">E</span>EnglAI</a><a class="button secondary" href="/student/skill.php?skill=speaking">← Speaking</a></header><main class="game-shell"><section id="speaking-game" class="card speaking-game" data-session-id="<?=$state['id']?>" data-csrf="<?=htmlspecialchars(Csrf::token())?>"><script type="application/json" data-speaking-state><?=json_encode($state,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_UNICODE)?></script><div data-speaking-host></div></section></main><script src="/assets/js/speaking-game.js" defer></script></body></html>
