<?php
declare(strict_types=1);
return static function(PDO $pdo):void{
$has=static function(string $t,string $c)use($pdo):bool{$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?');$q->execute([$t,$c]);return(bool)$q->fetchColumn();};
$pdo->exec("CREATE TABLE IF NOT EXISTS users(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,role ENUM('teacher','student') NOT NULL,email VARCHAR(190) NOT NULL,name VARCHAR(120) NOT NULL,password_hash VARCHAR(255) NOT NULL,status ENUM('active','blocked','disabled','pending') NOT NULL DEFAULT 'active',avatar VARCHAR(32) NULL,remember_token_hash CHAR(64) NULL,remember_expires_at DATETIME NULL,last_login_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_users_email(email),KEY idx_users_role_status(role,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
if(!$has('classrooms','teacher_user_id'))$pdo->exec('ALTER TABLE classrooms ADD COLUMN teacher_user_id BIGINT UNSIGNED NULL AFTER teacher_key,ADD KEY idx_classrooms_teacher_user(teacher_user_id),ADD CONSTRAINT fk_classroom_teacher_user FOREIGN KEY(teacher_user_id) REFERENCES users(id) ON DELETE RESTRICT');
foreach(['description'=>'TEXT NULL','grade'=>'VARCHAR(60) NULL','code_visible'=>'TINYINT(1) NOT NULL DEFAULT 1','join_open'=>'TINYINT(1) NOT NULL DEFAULT 1','require_approval'=>'TINYINT(1) NOT NULL DEFAULT 0','self_learning_enabled'=>'TINYINT(1) NOT NULL DEFAULT 1','live_quiz_review_enabled'=>'TINYINT(1) NOT NULL DEFAULT 1','leaderboard_visible'=>'TINYINT(1) NOT NULL DEFAULT 1','microphone_notice'=>"VARCHAR(500) NOT NULL DEFAULT 'Microphone is used only to create a transcript; audio is not stored.'",'listening_replay_limit'=>'TINYINT UNSIGNED NOT NULL DEFAULT 2','timezone'=>"VARCHAR(64) NOT NULL DEFAULT 'Asia/Jakarta'",'language'=>"VARCHAR(10) NOT NULL DEFAULT 'id'"] as $c=>$d)if(!$has('classrooms',$c))$pdo->exec("ALTER TABLE classrooms ADD COLUMN {$c} {$d}");
if(!$has('classroom_members','user_id'))$pdo->exec("ALTER TABLE classroom_members ADD COLUMN user_id BIGINT UNSIGNED NULL AFTER classroom_id,ADD COLUMN membership_status ENUM('pending','active','removed','blocked','left','archived') NOT NULL DEFAULT 'active',ADD COLUMN approved_at DATETIME NULL,ADD COLUMN removed_at DATETIME NULL,ADD KEY idx_members_user_status(user_id,membership_status),ADD CONSTRAINT fk_member_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL");
$pdo->exec("CREATE TABLE IF NOT EXISTS classroom_code_history(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,classroom_id BIGINT UNSIGNED NOT NULL,old_code VARCHAR(16) NOT NULL,new_code VARCHAR(16) NOT NULL,changed_by BIGINT UNSIGNED NULL,changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_code_history(classroom_id,changed_at),CONSTRAINT fk_code_classroom FOREIGN KEY(classroom_id) REFERENCES classrooms(id) ON DELETE CASCADE,CONSTRAINT fk_code_actor FOREIGN KEY(changed_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$pdo->exec("CREATE TABLE IF NOT EXISTS login_attempts(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,identity_hash CHAR(64) NOT NULL,ip_hash CHAR(64) NOT NULL,succeeded TINYINT(1) NOT NULL,attempted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_login_rate(identity_hash,ip_hash,attempted_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$pdo->exec("CREATE TABLE IF NOT EXISTS guest_account_claims(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,member_id BIGINT UNSIGNED NOT NULL,claim_token_hash CHAR(64) NOT NULL,claimed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_claim_member(member_id),CONSTRAINT fk_claim_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_claim_member FOREIGN KEY(member_id) REFERENCES classroom_members(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$pdo->exec("ALTER TABLE classroom_members ADD UNIQUE KEY uq_member_user_classroom(classroom_id,user_id)");
};
