<?php
declare(strict_types=1);
return static function(PDO $pdo):void{
$sql=[
"CREATE TABLE IF NOT EXISTS analytics_snapshots(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,classroom_id BIGINT UNSIGNED NOT NULL,snapshot_type VARCHAR(40) NOT NULL,period_start DATE NULL,period_end DATE NULL,metrics_json JSON NOT NULL,calculated_at DATETIME NOT NULL,UNIQUE KEY uq_snapshot(classroom_id,snapshot_type,period_start,period_end),KEY idx_snapshot_classroom(classroom_id,calculated_at),CONSTRAINT fk_snapshot_classroom FOREIGN KEY(classroom_id) REFERENCES classrooms(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
"CREATE TABLE IF NOT EXISTS teacher_reviews(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,classroom_id BIGINT UNSIGNED NOT NULL,assessment_context ENUM('self_learning','live_quiz') NOT NULL,assessment_id BIGINT UNSIGNED NOT NULL,member_id BIGINT UNSIGNED NOT NULL,reviewer VARCHAR(100) NOT NULL,comment TEXT NULL,status ENUM('reviewed','revised') NOT NULL DEFAULT 'reviewed',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_review_context(classroom_id,assessment_context,assessment_id),CONSTRAINT fk_review_classroom FOREIGN KEY(classroom_id) REFERENCES classrooms(id) ON DELETE CASCADE,CONSTRAINT fk_review_member FOREIGN KEY(member_id) REFERENCES classroom_members(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
"CREATE TABLE IF NOT EXISTS score_overrides(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,teacher_review_id BIGINT UNSIGNED NOT NULL,classroom_id BIGINT UNSIGNED NOT NULL,assessment_context ENUM('self_learning','live_quiz') NOT NULL,assessment_id BIGINT UNSIGNED NOT NULL,original_score DECIMAL(8,2) NOT NULL,previous_final_score DECIMAL(8,2) NOT NULL,new_score DECIMAL(8,2) NOT NULL,criterion_changes_json JSON NOT NULL,reason VARCHAR(500) NOT NULL,reviewer VARCHAR(100) NOT NULL,request_id VARCHAR(32) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_override_assessment(classroom_id,assessment_context,assessment_id,created_at),CONSTRAINT fk_override_review FOREIGN KEY(teacher_review_id) REFERENCES teacher_reviews(id) ON DELETE RESTRICT,CONSTRAINT fk_override_classroom FOREIGN KEY(classroom_id) REFERENCES classrooms(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
"CREATE TABLE IF NOT EXISTS audit_logs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,classroom_id BIGINT UNSIGNED NULL,actor VARCHAR(100) NOT NULL,action VARCHAR(80) NOT NULL,entity_type VARCHAR(60) NOT NULL,entity_id BIGINT UNSIGNED NULL,before_json JSON NULL,after_json JSON NULL,reason VARCHAR(500) NULL,request_id VARCHAR(32) NOT NULL,ip_hash CHAR(64) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_audit_classroom(classroom_id,created_at),KEY idx_audit_entity(entity_type,entity_id),CONSTRAINT fk_audit_classroom FOREIGN KEY(classroom_id) REFERENCES classrooms(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
"CREATE TABLE IF NOT EXISTS ai_recommendations(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,classroom_id BIGINT UNSIGNED NOT NULL,member_id BIGINT UNSIGNED NULL,metrics_hash CHAR(64) NOT NULL,recommendation_json JSON NOT NULL,source ENUM('ai','fallback') NOT NULL,status ENUM('active','accepted','dismissed','superseded') NOT NULL DEFAULT 'active',created_by VARCHAR(100) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_recommendation_scope(classroom_id,member_id,status,created_at),CONSTRAINT fk_recommendation_classroom FOREIGN KEY(classroom_id) REFERENCES classrooms(id) ON DELETE CASCADE,CONSTRAINT fk_recommendation_member FOREIGN KEY(member_id) REFERENCES classroom_members(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
"CREATE TABLE IF NOT EXISTS export_jobs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,classroom_id BIGINT UNSIGNED NOT NULL,export_type ENUM('classroom_csv','student_csv','quiz_csv','classroom_print','student_print') NOT NULL,member_id BIGINT UNSIGNED NULL,quiz_session_id BIGINT UNSIGNED NULL,requested_by VARCHAR(100) NOT NULL,status ENUM('completed','failed') NOT NULL,filename VARCHAR(255) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_export_classroom(classroom_id,created_at),CONSTRAINT fk_export_classroom FOREIGN KEY(classroom_id) REFERENCES classrooms(id) ON DELETE CASCADE,CONSTRAINT fk_export_member FOREIGN KEY(member_id) REFERENCES classroom_members(id) ON DELETE SET NULL,CONSTRAINT fk_export_quiz FOREIGN KEY(quiz_session_id) REFERENCES quiz_sessions(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
];foreach($sql as $s)$pdo->exec($s);
};
