<?php
declare(strict_types=1);require_once __DIR__.'/_auth.php';require_once __DIR__.'/../vendor/autoload.php';
use EnglAI\Analytics\AnalyticsService;use EnglAI\Mvp\ClassroomService;use EnglAI\Security\Csrf;
require_admin();$id=(int)($_GET['classroom_id']??0);$teacher=(string)($_SESSION['admin_username']??env_value('ADMIN_USERNAME','admin'));$classroom=(new ClassroomService(db()))->requireOwned($id,$teacher);$data=(new AnalyticsService(db()))->classroom($id,$_GET);
$q=db()->prepare('SELECT * FROM classroom_members WHERE classroom_id=? ORDER BY last_seen_at DESC,id DESC LIMIT 50');$q->execute([$id]);$members=$q->fetchAll();$q=db()->prepare("SELECT * FROM ai_recommendations WHERE classroom_id=? AND member_id IS NULL AND status='active' ORDER BY id DESC LIMIT 1");$q->execute([$id]);$rec=$q->fetch();$recommendation=$rec?json_decode($rec['recommendation_json'],true):null;
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Classroom Analytics · EnglAI</title><link rel="stylesheet" href="/assets/css/mvp.css"><link rel="stylesheet" href="/assets/css/analytics.css"></head><body><div class="stars" aria-hidden="true"></div><header class="nav"><a class="brand" href="/admin/"><span class="brand-mark">E</span>EnglAI</a><a class="button secondary" href="/admin/classroom.php?id=<?=$id?>">← Classroom</a></header><main class="shell">
<section class="card dashboard-hero"><span class="eyebrow">System-calculated metrics</span><h1><?=htmlspecialchars($classroom['name'])?> <span class="gradient-text">Analytics</span></h1><p class="muted">Dihitung deterministik dari attempts, answers, assessments, dan quiz results nyata.</p><div class="row"><a class="button secondary" href="/admin/export.php?classroom_id=<?=$id?>">Export Data</a><a class="button secondary" href="/admin/report.php?classroom_id=<?=$id?>">Print Report</a><a class="button secondary" href="/admin/audit.php?classroom_id=<?=$id?>">Audit Log</a></div></section>
<form class="card grid four" method="get" aria-label="Analytics filters"><input type="hidden" name="classroom_id" value="<?=$id?>"><label>Date from<input type="date" name="date_from" value="<?=htmlspecialchars($data['filters']['date_from'])?>"></label><label>Date to<input type="date" name="date_to" value="<?=htmlspecialchars($data['filters']['date_to'])?>"></label><label>Skill<select name="skill"><option value="">All</option><?php foreach(['reading','listening','speaking','writing'] as $s):?><option <?=$data['filters']['skill']===$s?'selected':''?>><?=$s?></option><?php endforeach;?></select></label><label>Level<select name="level"><option value="">All</option><?php foreach(['basic','intermediate','advanced'] as $l):?><option <?=$data['filters']['level']===$l?'selected':''?>><?=$l?></option><?php endforeach;?></select></label><button class="button secondary">Apply Validated Filters</button></form>
<section class="grid four analytics-metrics"><?php foreach([['Students',$data['students']],['Active (30d)',$data['active_students']],['Self Learning Attempts',$data['self_learning_attempts']],['Live Quiz Sessions',$data['live_quiz_sessions']],['Self Learning Avg',$data['self_learning_average'].'%'],['Live Quiz Avg',$data['live_quiz_average'].'%'],['Completion',$data['completion_rate'].'%'],['Classroom Level',ucfirst($data['classroom_level'])]] as $m):?><article class="card metric"><div><div class="stat"><?=htmlspecialchars((string)$m[1])?></div><span class="muted"><?=htmlspecialchars($m[0])?></span></div></article><?php endforeach;?></section>
<section class="grid two"><article class="card"><h2>Skill Performance</h2><?php foreach($data['skills'] as $skill=>$v):?><div class="metric-bar"><div class="row"><b><?=ucfirst($skill)?></b><span><?=$v['average']?>% · <?=$v['attempts']?> attempts</span></div><div class="progress-track" role="img" aria-label="<?=ucfirst($skill)?> average <?=$v['average']?> percent"><span style="width:<?=min(100,$v['average'])?>%"></span></div></div><?php endforeach;?></article>
<article class="card"><h2>Level Performance</h2><table><thead><tr><th>Level</th><th class="text-right">Available</th><th class="text-right">Completed</th><th class="text-right">Students</th><th class="text-right">Average</th></tr></thead><tbody><?php foreach($data['levels'] as $r):?><tr><td><?=ucfirst($r['level'])?></td><td class="text-right"><?=(int)$r['available']?></td><td class="text-right"><?=(int)$r['completed']?></td><td class="text-right"><?=(int)$r['students']?></td><td class="text-right"><?=number_format((float)$r['average'],1)?>%</td></tr><?php endforeach;?></tbody></table></article></section>
<section class="grid two"><article class="card"><h2>Activity Trends · 30 Days</h2><?php if(!$data['trends']):?><div class="empty">Belum cukup aktivitas untuk membuat analisis.</div><?php else:?><div class="trend-chart"><?php foreach($data['trends'] as $r):?><div class="trend-column"><span style="height:<?=max(8,min(100,(int)$r['activities']*10))?>%"></span><small><?=htmlspecialchars(substr($r['day'],5))?></small><b><?=(int)$r['activities']?></b></div><?php endforeach;?></div><?php endif;?></article>
<article class="card"><h2>AI Teaching Recommendation</h2><?php if($recommendation):?><p><?=htmlspecialchars($recommendation['summary'])?></p><ul><?php foreach($recommendation['recommended_actions'] as $a):?><li><?=htmlspecialchars($a)?></li><?php endforeach;?></ul><span class="badge dev"><?=htmlspecialchars(strtoupper($rec['source']))?></span><?php else:?><div class="empty">Generate recommendation hanya saat diperlukan.</div><?php endif;?><p class="muted">Rekomendasi AI membantu Teacher mengambil keputusan dan tidak menggantikan penilaian profesional Teacher.</p><form method="post" action="/admin/generate_recommendation.php"><?=Csrf::field()?><input type="hidden" name="classroom_id" value="<?=$id?>"><button class="button gold">Generate / Refresh Recommendation</button></form></article></section>
<section class="card"><h2>Competency Analysis</h2><?php if(!$data['competencies']):?><div class="empty">Belum cukup aktivitas untuk membuat analisis.</div><?php else:?><table><thead><tr><th>Competency</th><th class="text-right">Items</th><th class="text-right">Students</th><th class="text-right">Attempts</th><th class="text-right">Average</th><th class="text-center">Status</th></tr></thead><tbody><?php foreach($data['competencies'] as $r):?><tr><td><?=htmlspecialchars($r['competency'])?></td><td class="text-right"><?=(int)$r['items']?></td><td class="text-right"><?=(int)$r['students']?></td><td class="text-right"><?=(int)$r['attempts']?></td><td class="text-right"><?=number_format((float)$r['average'],1)?>%</td><td class="text-center"><span class="badge <?=$r['status']==='Mastered'?'available':($r['status']==='Developing'?'dev':'danger')?>"><?=$r['status']?></span></td></tr><?php endforeach;?></tbody></table><?php endif;?></section>

<section class="card"><h2>Student Identities</h2><p class="muted">Identity berdasarkan internal member/session ID; cookie yang dihapus atau perangkat berbeda menghasilkan identity terpisah.</p><table><thead><tr><th>ID</th><th>Display Name</th><th>Joined</th><th>Latest</th><th class="text-right"></th></tr></thead><tbody><?php foreach($members as $m):?><tr><td>#<?=(int)$m['id']?></td><td><?=htmlspecialchars($m['display_name']?:'Student')?></td><td><?=htmlspecialchars($m['created_at'])?></td><td><?=htmlspecialchars($m['last_seen_at']?:'—')?></td><td class="text-right"><a class="button secondary" href="/admin/student_analytics.php?classroom_id=<?=$id?>&member_id=<?=(int)$m['id']?>">Open</a></td></tr><?php endforeach;?></tbody></table></section>
</main><script src="/assets/js/visual-effects.js" defer></script></body></html>
