<?php
declare(strict_types=1);require_once __DIR__.'/_auth.php';require_once __DIR__.'/../vendor/autoload.php';
use EnglAI\Analytics\OverrideService;use EnglAI\Mvp\ClassroomService;use EnglAI\Security\Csrf;
require_admin();$cid=(int)($_GET['classroom_id']??$_POST['classroom_id']??0);$aid=(int)($_GET['answer_id']??$_POST['answer_id']??0);$actor=(string)($_SESSION['admin_username']??'admin');(new ClassroomService(db()))->requireOwned($cid,$actor);
if($_SERVER['REQUEST_METHOD']==='POST'){Csrf::requireValid($_POST['csrf_token']??null);(new OverrideService(db()))->overrideLiveQuiz($cid,$aid,(float)($_POST['new_score']??0),['teacher_comment'=>trim((string)($_POST['comment']??''))],(string)($_POST['reason']??''),$actor);header("Location: /admin/assessment_review.php?classroom_id={$cid}&answer_id={$aid}&saved=1");exit;}
$q=db()->prepare("SELECT a.*,s.question,s.skill,s.content_json,p.member_id,p.display_name,q.title FROM quiz_answers a JOIN quiz_session_questions s ON s.id=a.session_question_id JOIN quiz_participants p ON p.id=a.participant_id JOIN quiz_sessions q ON q.id=a.quiz_session_id WHERE a.id=? AND q.classroom_id=? AND s.skill IN('speaking','writing')");$q->execute([$aid,$cid]);$a=$q->fetch();if(!$a){http_response_code(404);exit('Assessment tidak ditemukan.');}$rubric=json_decode((string)$a['rubric_json'],true)?:[];$q=db()->prepare("SELECT * FROM score_overrides WHERE classroom_id=? AND assessment_context='live_quiz' AND assessment_id=? ORDER BY id DESC");$q->execute([$cid,$aid]);$history=$q->fetchAll();
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Assessment Review · EnglAI</title><link rel="stylesheet" href="/assets/css/mvp.css"></head><body><div class="stars"></div><header class="nav"><a class="brand" href="/admin/">EnglAI</a><a class="button secondary" href="/admin/student_analytics.php?classroom_id=<?=$cid?>&member_id=<?=(int)$a['member_id']?>">← Student</a></header><main class="shell"><section class="card dashboard-hero"><span class="eyebrow"><?=ucfirst($a['skill'])?> Assessment</span><h1>Teacher Review</h1><p><?=htmlspecialchars($a['question'])?></p></section><?php if(isset($_GET['saved'])):?><div class="alert ok">Score reviewed by Teacher.</div><?php endif;?>
<section class="grid two"><article class="card"><h2>Original Submission</h2><p><?=nl2br(htmlspecialchars((string)($a['skill']==='speaking'?$a['transcript']:$a['writing_submission'])))?></p><h3>Original AI/Fallback Rubric</h3><?php foreach($rubric['criteria']??[] as $c):?><p><b><?=htmlspecialchars($c['name'])?></b>: <?=htmlspecialchars((string)$c['score'])?>/100</p><?php endforeach;?><p>Source: <?=htmlspecialchars((string)$a['assessment_source'])?></p></article>
<article class="card"><h2>Override Score</h2><form method="post"><?=Csrf::field()?><input type="hidden" name="classroom_id" value="<?=$cid?>"><input type="hidden" name="answer_id" value="<?=$aid?>"><label>New score (0–1000)<input type="number" name="new_score" min="0" max="1000" value="<?=(int)$a['score']?>" required></label><label>Teacher comment<textarea name="comment" maxlength="1000"></textarea></label><label>Required reason<textarea name="reason" minlength="5" maxlength="500" required></textarea></label><button class="button gold">Save Reviewed Score</button></form></article></section><section class="card"><h2>Immutable Override History</h2><table><thead><tr><th>Previous</th><th>New</th><th>Reason</th><th>Reviewer</th><th>Time</th></tr></thead><tbody><?php foreach($history as $h):?><tr><td><?=$h['previous_final_score']?></td><td><?=$h['new_score']?></td><td><?=htmlspecialchars($h['reason'])?></td><td><?=htmlspecialchars($h['reviewer'])?></td><td><?=htmlspecialchars($h['created_at'])?></td></tr><?php endforeach;?></tbody></table></section></main></body></html>
