<?php
declare(strict_types=1);
require_once __DIR__.'/_auth.php';require_once __DIR__.'/../vendor/autoload.php';
use EnglAI\Mvp\ClassroomService;use EnglAI\Security\Csrf;
require_admin();$teacher=(string)($_SESSION['admin_username']??env_value('ADMIN_USERNAME','admin'));
try{$classroom=(new ClassroomService(db()))->requireOwned((int)($_GET['id']??0),$teacher);}catch(Throwable){http_response_code(404);exit('Classroom tidak ditemukan.');}
$id=(int)$classroom['id'];$message=trim((string)($_GET['message']??''));
$stmt=db()->prepare('SELECT * FROM classroom_lesson_plans WHERE classroom_id=? AND is_active=1 ORDER BY version DESC LIMIT 1');$stmt->execute([$id]);$rpp=$stmt->fetch();
$stmt=db()->prepare('SELECT content_type,source,COUNT(*) total,MAX(created_at) generated_at FROM content_questions WHERE classroom_id=? GROUP BY content_type,source');$stmt->execute([$id]);$bankRows=$stmt->fetchAll();$banks=[];$source='—';$generatedAt=null;foreach($bankRows as $row){$banks[$row['content_type']]=($banks[$row['content_type']]??0)+(int)$row['total'];$source=$row['source'];$generatedAt=$row['generated_at'];}
$stmt=db()->prepare('SELECT display_name,avatar,last_seen_at,created_at FROM classroom_members WHERE classroom_id=? ORDER BY created_at DESC LIMIT 30');$stmt->execute([$id]);$members=$stmt->fetchAll();
$stmt=db()->prepare('SELECT id,state,question_count,difficulty,created_at FROM quiz_sessions WHERE classroom_id=? ORDER BY id DESC LIMIT 12');$stmt->execute([$id]);$quizzes=$stmt->fetchAll();
$analysis=['topic'=>$rpp?pathinfo($rpp['original_name'],PATHINFO_FILENAME):'Belum tersedia','objectives'=>'Menunggu RPP classroom','vocabulary'=>'—','grammar'=>'Teridentifikasi saat content generation','level'=>'Intermediate'];
if($rpp){preg_match_all('/\b[A-Za-z]{5,}\b/u',(string)$rpp['extracted_text'],$m);$words=array_values(array_unique(array_map('strtolower',$m[0]??[])));$words=array_slice(array_filter($words,fn($w)=>!in_array($w,['teacher','student','learning','bahasa','inggris'],true)),0,6);$analysis['objectives']='Teks berhasil diekstrak · '.number_format(mb_strlen($rpp['extracted_text'])).' karakter';$analysis['vocabulary']=$words?implode(', ',$words):'Menunggu analisis vocabulary';}
$ready=(int)($banks['self_learning']??0)>=20&&(int)($banks['live_quiz']??0)>=20;
$stmt=db()->prepare("SELECT * FROM ai_analyses WHERE classroom_id=? AND status='valid' ORDER BY id DESC LIMIT 1");$stmt->execute([$id]);$storedAnalysis=$stmt->fetch();
if($storedAnalysis){$analysis=['topic'=>$storedAnalysis['topic'],'objectives'=>implode(' · ',json_decode($storedAnalysis['learning_objectives_json'],true)?:[]),'vocabulary'=>implode(', ',json_decode($storedAnalysis['vocabulary_json'],true)?:[]),'grammar'=>implode(', ',json_decode($storedAnalysis['grammar_json'],true)?:[]),'level'=>ucfirst($storedAnalysis['recommended_level'])];}
$stmt=db()->prepare("SELECT skill,level,COUNT(*) total,MAX(source) source FROM learning_activities WHERE classroom_id=? AND status='ready' GROUP BY skill,level");$stmt->execute([$id]);$learningMatrix=[];foreach($stmt->fetchAll() as $row)$learningMatrix[$row['skill']][$row['level']]=$row;
$stmt=db()->prepare("SELECT l.skill,COUNT(a.id) attempts,COALESCE(AVG(a.score),0) average_score FROM learning_activities l LEFT JOIN learning_attempts a ON a.activity_id=l.id AND a.status='completed' WHERE l.classroom_id=? GROUP BY l.skill");$stmt->execute([$id]);$skillStats=$stmt->fetchAll();
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($classroom['name'])?> · EnglAI</title><link rel="stylesheet" href="/assets/css/mvp.css"></head>
<body><div class="stars" aria-hidden="true"></div><header class="nav"><a class="brand" href="/admin/"><span class="brand-mark">E</span>EnglAI</a><a class="button secondary" href="/admin/">← Teacher Dashboard</a></header>
<main class="shell"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/admin/">Teacher</a><span>›</span><strong><?=htmlspecialchars($classroom['name'])?></strong></nav>
<section class="card dashboard-hero"><div class="toolbar"><div><span class="code"><?=htmlspecialchars($classroom['code'])?></span><h1><?=htmlspecialchars($classroom['name'])?></h1><p class="muted"><?=htmlspecialchars($rpp['original_name']??'Belum ada lesson plan')?></p></div><div class="row"><span class="badge <?=$ready?'available':'dev'?>"><?=$ready?'Content Ready':'Setup Required'?></span><button class="button secondary" data-copy="<?=htmlspecialchars($classroom['code'])?>">Copy Classroom ID</button></div></div></section>
<?php if($message):?><div class="alert ok" role="status"><?=htmlspecialchars($message)?></div><?php endif;?>
<nav class="tabs glass" aria-label="Classroom sections"><a class="active" href="#overview">Overview</a><a href="#lesson-plan">Lesson Plan</a><a href="#self-learning">Self Learning</a><a href="#live-quiz">Live Quiz</a><a href="#students">Students</a><a href="/admin/analytics.php?classroom_id=<?=$id?>">Analytics</a><a href="/admin/settings.php?classroom_id=<?=$id?>">Settings</a></nav>
<section id="overview" class="grid four"><article class="card metric"><div class="icon-box">👥</div><div><div class="stat"><?=count($members)?></div><span class="muted">Students</span></div></article><article class="card metric"><div class="icon-box">📚</div><div><div class="stat"><?=(int)($banks['self_learning']??0)?></div><span class="muted">Self Learning</span></div></article><article class="card metric"><div class="icon-box">🏆</div><div><div class="stat"><?=(int)($banks['live_quiz']??0)?></div><span class="muted">Live Quiz Bank</span></div></article><article class="card metric"><div class="icon-box">🎮</div><div><div class="stat"><?=count($quizzes)?></div><span class="muted">Quiz Sessions</span></div></article></section>
<section class="grid two" style="margin-top:22px">
<article class="card" id="lesson-plan"><div class="row" style="justify-content:space-between"><div><span class="eyebrow">Lesson Plan</span><h2>Upload RPP</h2></div><?php if($rpp):?><span class="badge available">Extracted</span><?php endif;?></div>
<?php if($rpp):?><p><b><?=htmlspecialchars($rpp['original_name'])?></b><br><small class="muted">Version <?=(int)$rpp['version']?> · <?=htmlspecialchars(strtoupper($rpp['file_type']))?> · text extraction ready</small></p><?php endif;?>
<form method="post" enctype="multipart/form-data" action="/admin/classroom_upload.php" data-upload-form><div class="dropzone" data-dropzone><div class="icon-box" style="margin:auto">⇧</div><h3>Drag & drop lesson plan</h3><p class="muted" data-file-status>PDF atau DOCX · Maksimal 15 MB</p><input type="file" name="rpp_file" accept=".pdf,.docx" required><?=Csrf::field()?><input type="hidden" name="classroom_id" value="<?=$id?>"><button class="button primary">Upload & Extract RPP</button><div class="generation-meter" style="margin-top:16px" aria-label="Upload progress"><span data-upload-progress style="width:0"></span></div><small class="muted" data-upload-message aria-live="polite"></small></div></form></article>
<article class="card"><div class="row" style="justify-content:space-between"><div><span class="eyebrow">AI Analysis</span><h2>Lesson insights</h2></div><span class="badge <?=$source==='ai'?'available':'dev'?>"><?=htmlspecialchars(strtoupper($source))?></span></div>
<div class="analysis-grid"><?php foreach([['Topic',$analysis['topic']],['Objectives',$analysis['objectives']],['Vocabulary',$analysis['vocabulary']],['Grammar',$analysis['grammar']],['AI Recommended Level',$analysis['level']],['Reason',$storedAnalysis['recommendation_reason']??'Run AI Analysis untuk rekomendasi terstruktur.']] as $item):?><div class="analysis-item"><small class="muted"><?=$item[0]?></small><br><b><?=htmlspecialchars((string)$item[1])?></b></div><?php endforeach;?></div>
<div class="grid two" style="margin-top:18px"><form method="post" action="/admin/analyze_rpp.php"><?=Csrf::field()?><input type="hidden" name="classroom_id" value="<?=$id?>"><button class="button secondary wide" <?=$rpp?'':'disabled'?>><?=$storedAnalysis?'Run Analysis Again':'Run AI Analysis'?></button></form>
<form method="post" action="/admin/confirm_level.php"><?=Csrf::field()?><input type="hidden" name="classroom_id" value="<?=$id?>"><label for="level">Classroom Default Level</label><select id="level" name="level"><?php foreach(['basic','intermediate','advanced'] as $level):?><option value="<?=$level?>" <?=$classroom['default_level']===$level?'selected':''?>><?=ucfirst($level)?></option><?php endforeach;?></select><button class="button primary wide">Confirm Level</button></form></div>
<form method="post" action="/admin/generate_content.php"><?=Csrf::field()?><input type="hidden" name="classroom_id" value="<?=$id?>"><button class="button ghost wide" <?=$rpp?'':'disabled'?>><?=$ready?'Regenerate Reading Live Quiz Banks':'Generate Reading Live Quiz Banks'?></button></form></article></section>
<section class="grid two" style="margin-top:22px"><article class="card" id="self-learning"><span class="eyebrow">Self Learning Content</span><h2>Generate Skill & Level</h2><p class="muted">Setiap generation membuat 3 modules dan minimal 10 activities tanpa menghapus level lama.</p><form method="post" action="/admin/generate_learning.php"><?=Csrf::field()?><input type="hidden" name="classroom_id" value="<?=$id?>"><div class="grid two"><div><label>Skill</label><select name="skill"><?php foreach(['reading','listening','speaking','writing'] as $skill):?><option value="<?=$skill?>"><?=ucfirst($skill)?></option><?php endforeach;?></select></div><div><label>Level</label><select name="level"><?php foreach(['basic','intermediate','advanced'] as $level):?><option value="<?=$level?>" <?=$classroom['default_level']===$level?'selected':''?>><?=ucfirst($level)?></option><?php endforeach;?></select></div></div><button class="button gold wide">Generate Self Learning</button></form>
<table><thead><tr><th>Skill</th><th>Basic</th><th>Intermediate</th><th>Advanced</th></tr></thead><tbody><?php foreach(['reading','listening','speaking','writing'] as $skill):?><tr><td><?=ucfirst($skill)?></td><?php foreach(['basic','intermediate','advanced'] as $level):$cell=$learningMatrix[$skill][$level]??null;?><td><span class="badge <?=$cell?'available':'dev'?>"><?=$cell?(int)$cell['total'].' ready':'Not generated'?></span></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></article>
<article class="card" id="live-quiz"><span class="eyebrow">Multi-Skill Live Quiz</span><h2>Create live session</h2><p class="muted">Reading, Listening, AI Speaking Feedback, Writing, Mixed Skills, atau Final Challenge dengan server timer dan scoring backend.</p><a class="button primary wide" href="/admin/quiz_wizard.php?classroom_id=<?=$id?>">Open Live Quiz Wizard →</a></article></section>
<section class="card" id="students" style="margin-top:22px"><div class="row" style="justify-content:space-between"><h2>Students</h2><span class="status"><?=count($members)?> membership records</span></div><?php if(!$members):?><div class="empty">Bagikan Classroom ID agar Student dapat bergabung.</div><?php else:?><table><thead><tr><th>Student</th><th>Avatar</th><th>Status</th><th>Last seen</th><th>Control</th></tr></thead><tbody><?php foreach($members as $m):?><tr><td><?=htmlspecialchars($m['display_name']?:'Joined Student')?></td><td><?=htmlspecialchars($m['avatar']?:'—')?></td><td><span class="badge"><?=htmlspecialchars($m['membership_status']??'active')?></span></td><td><?=htmlspecialchars($m['last_seen_at']?:$m['created_at'])?></td><td><form method="post" action="/admin/membership_action.php" class="row"><?=Csrf::field()?><input type="hidden" name="classroom_id" value="<?=$id?>"><input type="hidden" name="member_id" value="<?=(int)$m['id']?>"><?php if(($m['membership_status']??'active')==='pending'):?><button class="button secondary" name="action" value="approve">Approve</button><?php endif;?><button class="button secondary" name="action" value="remove">Remove</button><button class="button secondary" name="action" value="block">Block</button></form></td></tr><?php endforeach;?></tbody></table><?php endif;?></section>
<section class="card" style="margin-top:22px"><h2>Self Learning Progress</h2><table><thead><tr><th>Skill</th><th>Completed Attempts</th><th>Average Score</th></tr></thead><tbody><?php foreach($skillStats as $stat):?><tr><td><?=htmlspecialchars(ucfirst($stat['skill']))?></td><td><?=(int)$stat['attempts']?></td><td><?=number_format((float)$stat['average_score'],1)?>%</td></tr><?php endforeach;?></tbody></table></section>
<section class="card" style="margin-top:22px"><h2>Live Quiz History</h2><?php if(!$quizzes):?><div class="empty">Belum ada Live Quiz.</div><?php else:?><table><thead><tr><th>Session</th><th>State</th><th>Questions</th><th>Difficulty</th><th></th></tr></thead><tbody><?php foreach($quizzes as $q):?><tr><td>#<?=(int)$q['id']?></td><td><span class="badge <?=$q['state']==='ACTIVE'?'live':''?>"><?=htmlspecialchars($q['state'])?></span></td><td><?=(int)$q['question_count']?></td><td><?=htmlspecialchars($q['difficulty'])?></td><td><a class="button secondary" href="/admin/quiz.php?id=<?=(int)$q['id']?>">Open</a></td></tr><?php endforeach;?></tbody></table><?php endif;?></section>
</main><script src="/assets/js/visual-effects.js" defer></script><script src="/assets/js/teacher.js" defer></script></body></html>
