<?php
declare(strict_types=1);
require_once __DIR__.'/_auth.php';require_once __DIR__.'/../vendor/autoload.php';use EnglAI\Security\Csrf;use EnglAI\Auth\AccountService;
if(admin_is_authenticated()){header('Location: index.php');exit;}$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){Csrf::requireValid($_POST['csrf_token']??null);$configuredUser=env_value('ADMIN_USERNAME','');$configuredHash=env_value('ADMIN_PASSWORD_HASH','');$username=trim((string)($_POST['username']??''));$password=(string)($_POST['password']??'');
try{$user=(new AccountService(db()))->login($username,$password,'teacher');AccountService::establish($user);header('Location: index.php');exit;}catch(Throwable){if($configuredUser!==''&&$configuredHash!==''&&hash_equals($configuredUser,$username)&&password_verify($password,$configuredHash)){session_regenerate_id(true);$_SESSION['admin_authenticated_at']=time();$_SESSION['admin_username']=$configuredUser;$_SESSION['temporary_teacher_auth']=true;header('Location: index.php');exit;}$error='Email atau password tidak valid.';}}
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Teacher Login · EnglAI</title><link rel="stylesheet" href="/assets/css/mvp.css"></head><body><div class="stars" aria-hidden="true"></div><header class="nav"><a class="brand" href="/"><span class="brand-mark">E</span>EnglAI</a><a class="button secondary" href="/">← Public Page</a></header>
<main class="public-hero" style="max-width:980px"><section><span class="eyebrow">Teacher Workspace</span><h1 class="display">Bangun <span class="gradient-text">AI Classroom</span> Anda.</h1><p class="lead">Kelola RPP, content bank, Self Learning, dan Live Quiz dari dashboard Teacher.</p><div class="preview-window"><span class="badge available">Secure Session</span><span class="badge available">CSRF Protected</span><span class="badge available">Classroom Isolated</span></div></section>
<section class="card join-panel"><span class="eyebrow">Welcome back</span><h2>Teacher Login</h2><?php if($error):?><div class="alert error" role="alert"><?=htmlspecialchars($error,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?></div><?php endif;?><form method="post"><?=Csrf::field()?><label for="username">Email</label><input id="username" type="email" name="username" autocomplete="username" required><label for="password">Password</label><input id="password" type="password" name="password" autocomplete="current-password" required><button class="button primary wide">Masuk ke Teacher Dashboard</button></form><a class="button secondary wide" href="/auth/register.php?role=teacher">Register Teacher</a></section></main><script src="/assets/js/visual-effects.js" defer></script></body></html>
