<?php
declare(strict_types=1);
require_once __DIR__.'/_auth.php';require_once __DIR__.'/../vendor/autoload.php';
use EnglAI\Mvp\ClassroomService;use EnglAI\Security\Csrf;
require_admin();$id=(int)($_GET['classroom_id']??0);$teacher=(string)($_SESSION['admin_username']??env_value('ADMIN_USERNAME','admin'));$classroom=(new ClassroomService(db()))->requireOwned($id,$teacher);
$q=db()->prepare("SELECT skill,level,COUNT(*) total FROM live_quiz_items WHERE classroom_id=? AND status='ready' GROUP BY skill,level");$q->execute([$id]);$matrix=[];foreach($q->fetchAll() as $row)$matrix[$row['skill']][$row['level']]=(int)$row['total'];$message=(string)($_GET['message']??'');
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Live Quiz Wizard · EnglAI</title><link rel="stylesheet" href="/assets/css/mvp.css"><link rel="stylesheet" href="/assets/css/phase3.css"></head>
<body><div class="stars" aria-hidden="true"></div><header class="nav"><a class="brand" href="/admin/"><span class="brand-mark">E</span>EnglAI</a><a class="button secondary" href="/admin/classroom.php?id=<?=$id?>">← Classroom</a></header>
<main class="shell"><nav class="breadcrumb"><a href="/admin/">Teacher</a><span>›</span><a href="/admin/classroom.php?id=<?=$id?>"><?=htmlspecialchars($classroom['name'])?></a><span>›</span><strong>Live Quiz Wizard</strong></nav>
<section class="card dashboard-hero"><span class="eyebrow">Teacher Live Quiz Studio</span><h1>Create <span class="gradient-text">Multi-Skill Live Quiz</span></h1><p class="muted">Question snapshot, deadline, assessment, dan scoring dikendalikan backend.</p></section>
<?php if($message):?><div class="alert" role="status"><?=htmlspecialchars($message)?></div><?php endif;?>
<section class="grid two"><article class="card"><h2>Live Quiz Content Bank</h2><div class="bank-grid"><?php foreach(['reading','listening','speaking','writing'] as $skill):?><div class="bank-row"><b><?=ucfirst($skill)?></b><?php foreach(['basic','intermediate','advanced'] as $level):?><span class="badge <?=($matrix[$skill][$level]??0)>=10?'available':'dev'?>"><?=ucfirst($level)?>: <?=$matrix[$skill][$level]??0?></span><?php endforeach;?></div><?php endforeach;?></div>
<form method="post" action="/admin/generate_live_bank.php"><?=Csrf::field()?><input type="hidden" name="classroom_id" value="<?=$id?>"><div class="grid two"><select name="skill"><option value="all">All Skills</option><?php foreach(['reading','listening','speaking','writing'] as $s):?><option><?=$s?></option><?php endforeach;?></select><select name="level"><?php foreach(['basic','intermediate','advanced'] as $l):?><option value="<?=$l?>" <?=$classroom['default_level']===$l?'selected':''?>><?=ucfirst($l)?></option><?php endforeach;?></select></div><button class="button gold wide">Generate Live Quiz Content</button></form></article>
<article class="card"><h2>Wizard Guide</h2><ol class="step-list"><li>Quiz Mode & Skills</li><li>Difficulty</li><li>Question Count</li><li>Skill Distribution</li><li>Timer per Skill</li><li>Review & Open Lobby</li></ol></article></section>
<form method="post" action="/admin/create_quiz_v3.php" class="wizard-form"><?=Csrf::field()?><input type="hidden" name="classroom_id" value="<?=$id?>">
<section class="card wizard-step"><span class="step-number">1</span><h2>Quiz Mode</h2><div class="mode-grid"><?php foreach(['single_skill'=>'Single Skill','mixed_skills'=>'Mixed Skills','final_challenge'=>'Final Challenge'] as $v=>$label):?><label class="choice-tile"><input type="radio" name="quiz_mode" value="<?=$v?>" <?=$v==='single_skill'?'checked':''?>><b><?=$label?></b></label><?php endforeach;?></div><fieldset><legend>Skills</legend><div class="mode-grid"><?php foreach(['reading','listening','speaking','writing'] as $s):?><label class="choice-tile"><input type="checkbox" name="skills[]" value="<?=$s?>" <?=$s==='reading'?'checked':''?>><?=ucfirst($s)?></label><?php endforeach;?></div></fieldset></section>
<section class="card wizard-step"><span class="step-number">2</span><h2>Difficulty</h2><select name="level"><?php foreach(['basic','intermediate','advanced'] as $l):?><option value="<?=$l?>" <?=$classroom['default_level']===$l?'selected':''?>><?=ucfirst($l)?></option><?php endforeach;?></select></section>
<section class="card wizard-step"><span class="step-number">3</span><h2>Question Count</h2><input type="number" name="question_count" min="4" max="60" value="10" required></section>
<section class="card wizard-step"><span class="step-number">4</span><h2>Manual Distribution (optional)</h2><p class="muted">Kosongkan semua untuk automatic distribution.</p><div class="grid four"><?php foreach(['reading','listening','speaking','writing'] as $s):?><label><?=ucfirst($s)?><input type="number" name="distribution[<?=$s?>]" min="0" value="0"></label><?php endforeach;?></div><select name="question_order"><option value="mixed">Randomized shared order</option><option value="grouped">Grouped by skill</option></select></section>
<section class="card wizard-step"><span class="step-number">5</span><h2>Server Timer</h2><div class="grid four"><label>Reading<input name="timers[reading]" type="number" min="15" max="120" value="30"></label><label>Listening<input name="timers[listening]" type="number" min="15" max="120" value="40"></label><label>Speaking<input name="timers[speaking]" type="number" min="30" max="180" value="75"></label><label>Writing<input name="timers[writing]" type="number" min="60" max="600" value="180"></label></div></section>
<section class="card wizard-step final-step"><span class="step-number">6</span><h2>Review & Create</h2><label>Quiz title<input name="title" maxlength="200" placeholder="Optional title"></label><label class="row"><input type="checkbox" name="review_enabled" value="1" checked style="width:auto"> Allow personal review after quiz</label><div id="wizard-summary" class="summary-box" aria-live="polite"></div><button class="button gold wide">Create Quiz and Open Lobby</button></section></form></main>
<script src="/assets/js/visual-effects.js" defer></script><script src="/assets/js/quiz-wizard.js" defer></script></body></html>
