<?php
declare(strict_types=1);
require_once __DIR__.'/_auth.php';require_once __DIR__.'/../vendor/autoload.php';
use EnglAI\Mvp\ClassroomService;use EnglAI\Security\Csrf;
require_admin();$teacher=(string)($_SESSION['admin_username']??env_value('ADMIN_USERNAME','admin'));$quizId=(int)($_GET['id']??0);
$stmt=db()->prepare('SELECT q.*,c.name classroom_name,c.code classroom_code FROM quiz_sessions q JOIN classrooms c ON c.id=q.classroom_id WHERE q.id=?');$stmt->execute([$quizId]);$quiz=$stmt->fetch();if(!$quiz){http_response_code(404);exit('Quiz tidak ditemukan.');}(new ClassroomService(db()))->requireOwned((int)$quiz['classroom_id'],$teacher);
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Live Quiz #<?=$quizId?> · EnglAI</title><link rel="stylesheet" href="/assets/css/mvp.css"><link rel="stylesheet" href="/assets/css/game.css"><link rel="stylesheet" href="/assets/css/phase3.css"></head>
<body data-quiz-role="teacher" data-quiz-id="<?=$quizId?>" data-csrf="<?=htmlspecialchars(Csrf::token())?>"><div class="stars" aria-hidden="true"></div><header class="nav"><a class="brand" href="/admin/"><span class="brand-mark">E</span>EnglAI</a><a class="button secondary" href="/admin/classroom.php?id=<?=(int)$quiz['classroom_id']?>">← Classroom</a></header>
<main class="shell"><nav class="breadcrumb"><a href="/admin/">Teacher</a><span>›</span><a href="/admin/classroom.php?id=<?=(int)$quiz['classroom_id']?>"><?=htmlspecialchars($quiz['classroom_name'])?></a><span>›</span><strong>Live Quiz #<?=$quizId?></strong></nav>
<section class="card dashboard-hero"><div class="toolbar"><div><span class="eyebrow">Teacher Game Control</span><h1>Live Quiz <span class="gradient-text">#<?=$quizId?></span></h1><p class="muted"><?=htmlspecialchars($quiz['classroom_name'])?> · <span class="code"><?=htmlspecialchars($quiz['classroom_code'])?></span></p></div><div class="row"><span id="state" class="badge live" aria-live="polite"><?=htmlspecialchars($quiz['state'])?></span><button class="button secondary" data-copy="<?=htmlspecialchars($quiz['classroom_code'])?>">Copy Classroom ID</button></div></div></section>
<section class="grid two"><article class="card"><div class="row" style="justify-content:space-between"><div><span id="lobby-eyebrow" class="eyebrow">Lobby</span><h2>Players (<span id="participant-count">0</span>)</h2></div><span id="lobby-status" class="status">● Waiting</span></div><div id="participants" class="avatar-grid" aria-live="polite"><div class="empty">Waiting for Students…</div></div><div class="row" style="margin-top:22px"><button id="start" class="button gold" type="button" data-quiz-action="start">Start Live Quiz</button><button id="next-btn" class="button primary" type="button" data-quiz-action="next" hidden>Next Question / End Question</button><button id="close" class="button secondary" type="button" data-quiz-action="close">Close Lobby</button></div></article>
<article class="card"><div class="row" style="justify-content:space-between"><h2>Current Round</h2><div class="timer-ring" aria-label="Server timer"><svg width="70" height="70" viewBox="0 0 70 70"><circle class="timer-bg" cx="35" cy="35" r="30"></circle><circle id="timer-value" class="timer-value" cx="35" cy="35" r="30"></circle></svg><span id="timer-text" class="timer-text">—</span></div></div><div id="teacher-question" aria-live="polite"><p class="muted">Lobby terbuka. Tunggu Student bergabung.</p></div><p id="live-status" class="muted" aria-live="assertive"></p></article></section>
<section class="card" style="margin-top:22px"><div id="podium" class="podium" hidden></div><h2>Leaderboard</h2><ol id="leaderboard" class="leaderboard" aria-live="polite"></ol></section></main>
<script src="/assets/js/visual-effects.js" defer></script><script src="/assets/js/live-quiz.js" defer></script></body></html>
