<?php
declare(strict_types=1);require_once __DIR__.'/_auth.php';require_once __DIR__.'/../vendor/autoload.php';
use EnglAI\Analytics\AnalyticsService;use EnglAI\Mvp\ClassroomService;use EnglAI\Security\Csrf;
require_admin();$cid=(int)($_GET['classroom_id']??0);$mid=(int)($_GET['member_id']??0);$actor=(string)($_SESSION['admin_username']??'admin');$classroom=(new ClassroomService(db()))->requireOwned($cid,$actor);$data=(new AnalyticsService(db()))->student($cid,$mid);
$q=db()->prepare("SELECT a.id,a.score,a.assessment_status,a.assessment_source,a.transcript,a.writing_submission,a.rubric_json,s.question,s.skill,q.title quiz_title FROM quiz_answers a JOIN quiz_session_questions s ON s.id=a.session_question_id JOIN quiz_sessions q ON q.id=a.quiz_session_id JOIN quiz_participants p ON p.id=a.participant_id WHERE q.classroom_id=? AND p.member_id=? AND s.skill IN('speaking','writing') ORDER BY a.id DESC");$q->execute([$cid,$mid]);$assessments=$q->fetchAll();
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Student Analytics · EnglAI</title><link rel="stylesheet" href="/assets/css/mvp.css"><link rel="stylesheet" href="/assets/css/analytics.css"></head><body><div class="stars"></div><header class="nav"><a class="brand" href="/admin/"><span class="brand-mark">E</span>EnglAI</a><a class="button secondary" href="/admin/analytics.php?classroom_id=<?=$cid?>">← Analytics</a></header><main class="shell">
<section class="card dashboard-hero"><span class="eyebrow">Student Identity #<?=$mid?></span><h1><?=htmlspecialchars($data['member']['display_name']?:'Student')?> <span class="gradient-text">Progress</span></h1><p class="muted"><?=htmlspecialchars($classroom['name'])?> · joined <?=htmlspecialchars($data['member']['created_at'])?> · latest <?=htmlspecialchars($data['member']['last_seen_at']?:'—')?></p><div class="row"><span class="badge available">Strongest: <?=htmlspecialchars(ucfirst($data['strongest_skill']?:'insufficient data'))?></span><span class="badge dev">Improve: <?=htmlspecialchars(ucfirst($data['weakest_skill']?:'insufficient data'))?></span><a class="button secondary" href="/admin/export.php?classroom_id=<?=$cid?>&member_id=<?=$mid?>&type=student_csv">Export CSV</a></div></section>
<section class="grid four"><?php foreach($data['skills'] as $skill=>$v):?><article class="card"><h3><?=ucfirst($skill)?></h3><div class="stat"><?=$v['average_score']?>%</div><p class="muted"><?=$v['attempts']?> completed attempts</p></article><?php endforeach;?></section>
<?php if(!$data['skills']):?><div class="card empty">Belum cukup aktivitas untuk membuat analisis.</div><?php endif;?>
<section class="grid two"><article class="card"><h2>Recent Self Learning</h2><table><thead><tr><th>Activity</th><th>Skill</th><th>Level</th><th>Score</th></tr></thead><tbody><?php foreach($data['recent'] as $r):?><tr><td><?=htmlspecialchars($r['title'])?></td><td><?=ucfirst($r['skill'])?></td><td><?=ucfirst($r['level'])?></td><td><?=$r['score']?>%</td></tr><?php endforeach;?></tbody></table></article><article class="card"><h2>Historical Leaderboard</h2><table><thead><tr><th>Quiz</th><th>Rank</th><th>Score</th><th>Achievement</th></tr></thead><tbody><?php foreach($data['quiz_history'] as $r):?><tr><td><?=htmlspecialchars($r['title']?:'Quiz #'.$r['id'])?></td><td>#<?=htmlspecialchars((string)($r['final_rank']?:'—'))?></td><td><?=(int)$r['total_score']?></td><td><?=htmlspecialchars($r['achievement']?:'—')?></td></tr><?php endforeach;?></tbody></table></article></section>
<section class="card"><h2>Speaking & Writing Review</h2><p class="muted">AI Speaking Feedback berbasis transcription; bukan pronunciation assessment.</p><table><thead><tr><th>Quiz</th><th>Skill</th><th>Score</th><th>Source</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($assessments as $a):?><tr><td><?=htmlspecialchars($a['quiz_title'])?></td><td><?=ucfirst($a['skill'])?></td><td><?=(int)$a['score']?>/1000</td><td><?=htmlspecialchars((string)$a['assessment_source'])?></td><td><?=htmlspecialchars($a['assessment_status'])?></td><td><a class="button secondary" href="/admin/assessment_review.php?classroom_id=<?=$cid?>&answer_id=<?=(int)$a['id']?>">Review</a></td></tr><?php endforeach;?></tbody></table></section>
<section class="card"><h2>Personal Recommendation</h2><form method="post" action="/admin/generate_recommendation.php"><?=Csrf::field()?><input type="hidden" name="classroom_id" value="<?=$cid?>"><input type="hidden" name="member_id" value="<?=$mid?>"><button class="button gold">Generate Student Recommendation</button></form></section></main><script src="/assets/js/visual-effects.js" defer></script></body></html>
