<?php
declare(strict_types=1);
namespace EnglAI\Analytics;
final class AnalyticsService{
 public function __construct(private readonly \PDO $pdo){}
 public function refresh(int $id):array{$metrics=$this->classroom($id);$q=$this->pdo->prepare("INSERT INTO analytics_snapshots(classroom_id,snapshot_type,period_start,period_end,metrics_json,calculated_at) VALUES(?,'classroom_current',CURDATE(),CURDATE(),?,NOW()) ON DUPLICATE KEY UPDATE metrics_json=VALUES(metrics_json),calculated_at=NOW()");$q->execute([$id,json_encode($metrics,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR)]);return $metrics;}
 public function classroom(int $id,array $filters=[]):array{
  $filters=$this->validatedFilters($filters);
  $members=(int)$this->scalar('SELECT COUNT(*) FROM classroom_members WHERE classroom_id=?',[$id]);
  $active=(int)$this->scalar("SELECT COUNT(*) FROM classroom_members WHERE classroom_id=? AND last_seen_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)",[$id]);
  $attempts=(int)$this->scalar("SELECT COUNT(*) FROM learning_attempts WHERE classroom_id=? AND status='completed'",[$id]);
  $selfAvg=(float)$this->scalar("SELECT COALESCE(AVG(score),0) FROM learning_attempts WHERE classroom_id=? AND status='completed'",[$id]);
  $quizSessions=(int)$this->scalar("SELECT COUNT(*) FROM quiz_sessions WHERE classroom_id=? AND state IN('FINISHED','CLOSED')",[$id]);
  $quizAvg=(float)$this->scalar("SELECT COALESCE(AVG(a.normalized_score/10),0) FROM quiz_answers a JOIN quiz_sessions q ON q.id=a.quiz_session_id WHERE q.classroom_id=?",[$id]);
  $available=(int)$this->scalar("SELECT COUNT(*) FROM learning_activities WHERE classroom_id=? AND status='ready'",[$id]);
  $completedUnique=(int)$this->scalar("SELECT COUNT(DISTINCT CONCAT(member_id,':',activity_id)) FROM learning_attempts WHERE classroom_id=? AND status='completed'",[$id]);
  $level=(string)$this->scalar('SELECT default_level FROM classrooms WHERE id=?',[$id]);
  $latest=$this->scalar("SELECT MAX(x) FROM(SELECT MAX(completed_at)x FROM learning_attempts WHERE classroom_id=? UNION ALL SELECT MAX(finished_at) FROM quiz_sessions WHERE classroom_id=?)t",[$id,$id]);
  $skill=$this->skill($id);$levels=$this->levels($id);$trends=$this->trends($id);
  if($filters['skill']!=='')$skill=isset($skill[$filters['skill']])?[$filters['skill']=>$skill[$filters['skill']]]:[];
  if($filters['level']!=='')$levels=array_values(array_filter($levels,fn($row)=>$row['level']===$filters['level']));
  if($filters['date_from']!=='')$trends=array_values(array_filter($trends,fn($row)=>$row['day']>=$filters['date_from']));
  if($filters['date_to']!=='')$trends=array_values(array_filter($trends,fn($row)=>$row['day']<=$filters['date_to']));
  return ['students'=>$members,'active_students'=>$active,'inactive_students'=>max(0,$members-$active),'self_learning_attempts'=>$attempts,'live_quiz_sessions'=>$quizSessions,'self_learning_average'=>round($selfAvg,1),'live_quiz_average'=>round($quizAvg,1),'completion_rate'=>$members&&$available?round(min(100,$completedUnique/($members*$available)*100),1):0,'classroom_level'=>$level,'latest_activity'=>$latest,'skills'=>$skill,'levels'=>$levels,'trends'=>$trends,'competencies'=>$this->competencies($id),'questions'=>$this->questions($id),'rubrics'=>$this->rubrics($id),'filters'=>$filters];
 }
 public function student(int $classroom,int $member):array{
  $q=$this->pdo->prepare('SELECT * FROM classroom_members WHERE id=? AND classroom_id=?');$q->execute([$member,$classroom]);$m=$q->fetch();if(!$m)throw new \RuntimeException('Student identity tidak ditemukan.');
  $q=$this->pdo->prepare("SELECT l.skill,l.level,COUNT(*) attempts,ROUND(AVG(a.score),1) average_score,MAX(a.completed_at) latest FROM learning_attempts a JOIN learning_activities l ON l.id=a.activity_id WHERE a.classroom_id=? AND a.member_id=? AND a.status='completed' GROUP BY l.skill,l.level");$q->execute([$classroom,$member]);$rows=$q->fetchAll();
  $skill=[];foreach($rows as $r){$s=$r['skill'];$skill[$s]['attempts']=($skill[$s]['attempts']??0)+(int)$r['attempts'];$skill[$s]['scores'][]=(float)$r['average_score'];$skill[$s]['levels'][$r['level']]=$r;}
  foreach($skill as &$s)$s['average_score']=round(array_sum($s['scores'])/count($s['scores']),1);
  $ranked=$skill;uasort($ranked,fn($a,$b)=>$b['average_score']<=>$a['average_score']);$strong=array_key_first($ranked);$weak=$ranked?array_key_last($ranked):null;
  $q=$this->pdo->prepare("SELECT a.id,l.title,l.skill,l.level,a.score,a.completed_at FROM learning_attempts a JOIN learning_activities l ON l.id=a.activity_id WHERE a.classroom_id=? AND a.member_id=? AND a.status='completed' ORDER BY a.completed_at DESC LIMIT 20");$q->execute([$classroom,$member]);
  $recent=$q->fetchAll();$q=$this->pdo->prepare("SELECT q.id,q.title,q.quiz_mode,q.finished_at,p.total_score,p.final_rank,p.achievement FROM quiz_participants p JOIN quiz_sessions q ON q.id=p.quiz_session_id WHERE q.classroom_id=? AND p.member_id=? AND q.state IN('FINISHED','CLOSED') ORDER BY q.finished_at DESC");$q->execute([$classroom,$member]);
  return ['member'=>$m,'skills'=>$skill,'strongest_skill'=>$strong,'weakest_skill'=>$weak,'completed_activities'=>array_sum(array_column($rows,'attempts')),'self_learning_average'=>$rows?round(array_sum(array_column($rows,'average_score'))/count($rows),1):0,'recent'=>$recent,'quiz_history'=>$q->fetchAll()];
 }
 private function skill(int $id):array{$out=[];foreach(['reading','listening','speaking','writing'] as $s)$out[$s]=['attempts'=>0,'average'=>0,'completion'=>0];
  $q=$this->pdo->prepare("SELECT l.skill,COUNT(a.id) attempts,COALESCE(AVG(a.score),0) avgscore,COUNT(DISTINCT a.activity_id) completed,COUNT(DISTINCT l.id) available FROM learning_activities l LEFT JOIN learning_attempts a ON a.activity_id=l.id AND a.status='completed' WHERE l.classroom_id=? GROUP BY l.skill");$q->execute([$id]);foreach($q->fetchAll() as $r)$out[$r['skill']]=['attempts'=>(int)$r['attempts'],'average'=>round((float)$r['avgscore'],1),'completion'=>(int)$r['available']?round((int)$r['completed']/(int)$r['available']*100,1):0];return $out;}
 private function levels(int $id):array{$q=$this->pdo->prepare("SELECT l.level,COUNT(DISTINCT l.id) available,COUNT(a.id) completed,COUNT(DISTINCT a.member_id) students,COALESCE(AVG(a.score),0) average FROM learning_activities l LEFT JOIN learning_attempts a ON a.activity_id=l.id AND a.status='completed' WHERE l.classroom_id=? GROUP BY l.level");$q->execute([$id]);return $q->fetchAll();}
 private function trends(int $id):array{$q=$this->pdo->prepare("SELECT DATE(completed_at) day,COUNT(*) activities,ROUND(AVG(score),1) average_score FROM learning_attempts WHERE classroom_id=? AND status='completed' AND completed_at>=DATE_SUB(CURDATE(),INTERVAL 30 DAY) GROUP BY DATE(completed_at) ORDER BY day");$q->execute([$id]);return $q->fetchAll();}
 private function competencies(int $id):array{$threshold=(float)env_value('MASTERY_THRESHOLD_PERCENT','80');$q=$this->pdo->prepare("SELECT l.competency,COUNT(DISTINCT l.id) items,COUNT(DISTINCT a.member_id) students,COUNT(a.id) attempts,COALESCE(AVG(a.score),0) average FROM learning_activities l LEFT JOIN learning_attempts a ON a.activity_id=l.id AND a.status='completed' WHERE l.classroom_id=? GROUP BY l.competency ORDER BY average ASC");$q->execute([$id]);$rows=$q->fetchAll();foreach($rows as &$r){$r['mastery_rate']=(float)$r['average']>=$threshold?100:0;$r['status']=(float)$r['average']>=80?'Mastered':((float)$r['average']>=60?'Developing':'Needs Practice');}return $rows;}
 private function questions(int $id):array{$q=$this->pdo->prepare("SELECT s.id,s.skill,s.difficulty,s.question,COUNT(a.id) attempts,SUM(a.is_correct=1) correct,SUM(a.is_correct=0) incorrect,ROUND(AVG(a.response_ms),0) average_response_ms,ROUND(100*AVG(a.is_correct),1) correct_rate FROM quiz_session_questions s JOIN quiz_sessions q ON q.id=s.quiz_session_id LEFT JOIN quiz_answers a ON a.session_question_id=s.id WHERE q.classroom_id=? AND s.question_type IN('objective','listening_objective') GROUP BY s.id ORDER BY correct_rate ASC,attempts DESC LIMIT 100");$q->execute([$id]);$rows=$q->fetchAll();foreach($rows as &$r)$r['review_status']=(int)$r['attempts']>=5&&(float)$r['correct_rate']<30?'Needs Review':'Observed';return $rows;}
 private function rubrics(int $id):array{$q=$this->pdo->prepare("SELECT s.skill,a.rubric_json,a.assessment_source FROM quiz_answers a JOIN quiz_session_questions s ON s.id=a.session_question_id JOIN quiz_sessions q ON q.id=a.quiz_session_id WHERE q.classroom_id=? AND s.skill IN('speaking','writing') AND a.rubric_json IS NOT NULL");$q->execute([$id]);$out=[];foreach($q->fetchAll() as $r){$data=json_decode($r['rubric_json'],true)?:[];foreach($data['criteria']??[] as $c){$n=$c['name']??'criterion';$out[$r['skill']][$n]['sum']=($out[$r['skill']][$n]['sum']??0)+(float)($c['score']??0);$out[$r['skill']][$n]['count']=($out[$r['skill']][$n]['count']??0)+1;}}foreach($out as &$skills)foreach($skills as &$v)$v['average']=round($v['sum']/$v['count'],1);return $out;}
 public function validatedFilters(array $input):array{$out=[];foreach(['skill'=>['reading','listening','speaking','writing'],'level'=>['basic','intermediate','advanced'],'activity_type'=>['self_learning','live_quiz'],'source'=>['ai','fallback']] as $key=>$allowed){$value=(string)($input[$key]??'');$out[$key]=in_array($value,$allowed,true)?$value:'';}foreach(['date_from','date_to'] as $key){$value=(string)($input[$key]??'');$out[$key]=preg_match('/^\d{4}-\d{2}-\d{2}$/',$value)?$value:'';}$out['member_id']=max(0,(int)($input['member_id']??0));$out['page']=max(1,min(100000,(int)($input['page']??1)));return $out;}
 private function scalar(string $sql,array $args):mixed{$q=$this->pdo->prepare($sql);$q->execute($args);return $q->fetchColumn();}
}
