<?php
declare(strict_types=1);
$root=dirname(__DIR__,2);$page=file_get_contents($root.'/student/speaking.php');$js=file_get_contents($root.'/assets/js/speaking-game.js');$service=file_get_contents($root.'/src/Learning/SpeakingSessionService.php');$assessment=file_get_contents($root.'/src/Learning/AssessmentService.php');$migration=file_get_contents($root.'/database/migrations/202608020003_speaking_game_sessions.php');
$assert=static function(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);};
$assert(str_contains($service,'public const TASKS=10'),'Speaking must use 10 tasks.');
$assert(str_contains($service,"'read_aloud'")&&str_contains($service,"'guided_response'")&&str_contains($service,"'spontaneous_response'"),'Level task modes missing.');
$assert(str_contains($js,'MediaRecorder')&&str_contains($js,'getUserMedia'),'Original audio recording missing.');
$assert(str_contains($js,'deadline-Date.now()')&&str_contains($page,'INTERVAL 25 SECOND'),'Server-authoritative 25-second task timer missing.');
$assert(!preg_match('/background.?music|musicGain|localStorage/i',$js),'Speaking must not have background music.');
$assert(!str_contains($page,'Audio tidak disimpan oleh EnglAI'),'Old consent remains.');
$assert(str_contains($js,'The audio recording will not be sent to external AI services'),'Accurate privacy consent missing.');
$assert(str_contains($js,'SpeechRecognition')&&str_contains($js,'raw_transcript')&&str_contains($js,'transcript_confidence'),'Browser transcript contract missing.');
$assert(!str_contains($page,'$confidence<0.35)throw')&&!str_contains($page,'retryExhausted'),'Confidence and retry must not reject a transcript.');
$assert(str_contains($page,'$confidence<0.35?\'needs_review\'')&&str_contains($js,'mungkin perlu diperiksa kembali'),'Low-confidence warning behavior missing.');
$assert(str_contains($js,'Hasil transkrip sementara')&&!str_contains($js,'Rekam Ulang')&&str_contains($js,'Simpan & Lanjut'),'Single-attempt transcript preview flow missing.');
$assert(str_contains($js,'api("ready")')&&str_contains($js,'task_deadline_epoch_ms')&&str_contains($js,'api("recording_start")'),'Server deadline contract missing.');
$assert(str_contains($js,'Math.max(0,Math.min(25,raw))')&&str_contains($js,'timer.replaceChildren'),'Timer must render one bounded integer node.');
$assert(str_contains($service,'task_started_epoch_ms')&&str_contains($service,'task_deadline_epoch_ms')&&str_contains($service,'UNIX_TIMESTAMP(task_deadline_at)*1000'),'Unambiguous epoch-millisecond deadline missing.');
$assert(str_contains($service,'max(0,min(25'),'Timer bounds missing.');
$assert(str_contains($js,'api("no_response")')&&str_contains($js,'Waktu habis. Tidak ada rekaman yang dikirim.'),'No-response flow missing.');
$assert(str_contains($service,'$basicInstructions')&&str_contains($service,'$intermediateInstructions')&&str_contains($service,'$advancedInstructions'),'Indonesian level instructions missing.');
$assert(str_contains($service,'$seenTargets')&&str_contains($service,"'prompt'=>\$level==='basic'?\$target"),'Diversified Basic Read Aloud snapshot missing.');
$assert(!preg_match('/inline_data|audio_url|CURLFile|TRANSCRIPTION_API_URL/',$page.$assessment),'Audio must not be sent to an external AI service.');
$assert(str_contains($assessment,'basicReadAloud')&&str_contains($assessment,"'word_accuracy'")&&str_contains($assessment,'Teacher Review Required'),'Privacy-safe Basic assessment missing.');
$assert(str_contains($assessment,'de-identified')&&!str_contains($assessment,"'pronunciation'"),'Text-only de-identified assessment contract missing.');
$assert(str_contains($page,'storage/private/speaking')&&str_contains($page,'move_uploaded_file'),'Private upload missing.');
$assert(str_contains($page,"duration>26000")&&str_contains($page,'5*1024*1024'),'Upload bounds missing.');
$assert(str_contains($migration,'UNIQUE KEY uq_speaking_upload(session_id,task_id)'),'Idempotency constraint missing.');
$assert(!str_contains($js,'.innerHTML')&&!preg_match('/GEMINI_API_KEY|AIza[0-9A-Za-z_-]+/',$js),'Unsafe frontend content.');
echo "Speaking game targeted OK.\n";
